# syntax=docker/dockerfile:1@sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
#
# Code generated by factory from app.yaml and app.lock.yaml. DO NOT EDIT.
# Image: registry.example/hello (app hello on stack go)
#
# Rebuild bit-for-bit with `factory verify`, or directly with BuildKit
# (moby/buildkit:v0.33.1@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb):
#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \
#     --opt platform=linux/amd64,linux/arm64 \
#     --opt build-arg:SOURCE_DATE_EPOCH=1700000000 \
#     --output type=oci,dest=image.tar,rewrite-timestamp=true,$ANNOTATIONS
# from a context staged with `factory render --context-dir`, where
# $ANNOTATIONS (comma-separated) records the base for `factory rebase`:
#   annotation-manifest[linux/amd64].org.opencontainers.image.base.name=registry.example/go-run:latest
#   annotation-manifest[linux/amd64].org.opencontainers.image.base.digest=sha256:1111111111111111111111111111111111111111111111111111111111111111
#   annotation-manifest[linux/arm64].org.opencontainers.image.base.name=registry.example/go-run:latest
#   annotation-manifest[linux/arm64].org.opencontainers.image.base.digest=sha256:2222222222222222222222222222222222222222222222222222222222222222

ARG TARGETARCH

# ---- build: stack go ----
FROM --platform=$BUILDPLATFORM golang:1@sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc AS build
ARG TARGETOS TARGETARCH SOURCE_DATE_EPOCH
ENV APP_NAME="hello"
ENV CGO_ENABLED="0"
WORKDIR /src
COPY src/ /src/
RUN --mount=type=cache,target=/root/.cache/go-build,id=/root/.cache/go-build,sharing=locked --mount=type=cache,target=/go/pkg/mod,id=/go/pkg/mod,sharing=locked <<'FACTORY_EOF'
set -eu
mkdir -p /out
go mod download
FACTORY_EOF
RUN --mount=type=cache,target=/root/.cache/go-build,id=/root/.cache/go-build,sharing=locked --mount=type=cache,target=/go/pkg/mod,id=/go/pkg/mod,sharing=locked <<'FACTORY_EOF'
set -eu
go build -trimpath -o /out/hello .
FACTORY_EOF

# ---- app ----
FROM registry.example/go-run:latest@sha256:0000000000000000000000000000000000000000000000000000000000000000
COPY --link --from=build /out/ /app/
ENV PORT="8080"
USER 65532
ENTRYPOINT ["/app/hello"]
