# syntax=docker/dockerfile:1@sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
#
# Code generated by factory from image.yaml and image.lock.yaml. DO NOT EDIT.
# Image: registry.example/native
#
# Rebuild bit-for-bit with `clearcutt-factory verify`, or directly with BuildKit
# (moby/buildkit:v0.33.1@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb):
#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \
#     --opt platform=linux/amd64,linux/arm64 \
#     --opt build-arg:SOURCE_DATE_EPOCH=1700000000 \
#     --output type=oci,dest=image.tar,rewrite-timestamp=true
# from a context staged with `clearcutt-factory render --context-dir`.

ARG TARGETARCH

# ---- nix: ripgrep 1.0, fd 1.0 (verified: nix-signature) ----
FROM --platform=$BUILDPLATFORM nixos/nix:latest@sha256:nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn AS nix-amd64
ARG SOURCE_DATE_EPOCH
RUN nix --extra-experimental-features nix-command copy --from https://cache.nixos.org \
      /nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-ripgrep-1.0 \
      /nix/store/cccccccccccccccccccccccccccccccc-fd-1.0 \
 && mkdir -p /out/nix/store /out/usr/local/bin \
 && cp -a $(nix-store --query --requisites /nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-ripgrep-1.0 /nix/store/cccccccccccccccccccccccccccccccc-fd-1.0) /out/nix/store/ \
 && for p in /nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-ripgrep-1.0 /nix/store/cccccccccccccccccccccccccccccccc-fd-1.0; do for b in "$p"/bin/*; do if [ -e "$b" ]; then ln -sf "$b" /out/usr/local/bin/; fi; done; done

FROM --platform=$BUILDPLATFORM nixos/nix:latest@sha256:nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn AS nix-arm64
ARG SOURCE_DATE_EPOCH
RUN nix --extra-experimental-features nix-command copy --from https://cache.nixos.org \
      /nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-ripgrep-1.0 \
      /nix/store/dddddddddddddddddddddddddddddddd-fd-1.0 \
 && mkdir -p /out/nix/store /out/usr/local/bin \
 && cp -a $(nix-store --query --requisites /nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-ripgrep-1.0 /nix/store/dddddddddddddddddddddddddddddddd-fd-1.0) /out/nix/store/ \
 && for p in /nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-ripgrep-1.0 /nix/store/dddddddddddddddddddddddddddddddd-fd-1.0; do for b in "$p"/bin/*; do if [ -e "$b" ]; then ln -sf "$b" /out/usr/local/bin/; fi; done; done

FROM nix-${TARGETARCH} AS nix

# ---- image ----
# packages: apt (debian-13, snapshot 20261003T000000Z)
FROM scratch AS pkgs-amd64
ADD --checksum=sha256:9999999999999999999999999999999999999999999999999999999999999999 https://artifactory.example/debian-snapshot/archive/debian/20261003T000000Z/pool/main/j/jq/jq_1.7.1_amd64.deb /pkgs/jq_1.7.1_amd64.deb

FROM debian:trixie-slim@sha256:0000000000000000000000000000000000000000000000000000000000000000 AS packages-amd64
ARG SOURCE_DATE_EPOCH
RUN --mount=type=bind,from=pkgs-amd64,source=/pkgs,target=/tmp/factory-pkgs \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends /tmp/factory-pkgs/*.deb \
 && rm -rf /var/lib/apt/lists/* /var/cache/apt/*.bin /var/log/apt/* /var/log/dpkg.log /var/log/alternatives.log /var/cache/ldconfig/aux-cache /var/cache/debconf/*-old /var/lib/dpkg/*-old

FROM scratch AS pkgs-arm64
ADD --checksum=sha256:9999999999999999999999999999999999999999999999999999999999999999 https://artifactory.example/debian-snapshot/archive/debian/20261003T000000Z/pool/main/j/jq/jq_1.7.1_arm64.deb /pkgs/jq_1.7.1_arm64.deb

FROM debian:trixie-slim@sha256:0000000000000000000000000000000000000000000000000000000000000000 AS packages-arm64
ARG SOURCE_DATE_EPOCH
RUN --mount=type=bind,from=pkgs-arm64,source=/pkgs,target=/tmp/factory-pkgs \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends /tmp/factory-pkgs/*.deb \
 && rm -rf /var/lib/apt/lists/* /var/cache/apt/*.bin /var/log/apt/* /var/log/dpkg.log /var/log/alternatives.log /var/cache/ldconfig/aux-cache /var/cache/debconf/*-old /var/lib/dpkg/*-old

FROM packages-${TARGETARCH}
COPY --link --from=nix /out/ /
