# syntax=docker/dockerfile:1@sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
#
# Code generated by factory from image.yaml and image.lock.yaml. DO NOT EDIT.
# Image: registry.example/native
#
# Rebuild bit-for-bit with `factory verify`, or directly with BuildKit
# (moby/buildkit:v0.33.1@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb):
#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \
#     --opt platform=linux/amd64,linux/arm64 \
#     --opt build-arg:SOURCE_DATE_EPOCH=1700000000 \
#     --output type=oci,dest=image.tar,rewrite-timestamp=true
# from a context staged with `factory render --context-dir`.

ARG TARGETARCH

# ---- nix: ripgrep 1.0, fd 1.0 (verified: nix-signature) ----
FROM --platform=$BUILDPLATFORM nixos/nix:latest@sha256:nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn AS nix-amd64
ARG SOURCE_DATE_EPOCH
RUN nix --extra-experimental-features nix-command copy --from https://cache.nixos.org \
      /nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-ripgrep-1.0 \
      /nix/store/cccccccccccccccccccccccccccccccc-fd-1.0 \
 && mkdir -p /out/nix/store /out/usr/local/bin \
 && cp -a $(nix-store --query --requisites /nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-ripgrep-1.0 /nix/store/cccccccccccccccccccccccccccccccc-fd-1.0) /out/nix/store/ \
 && for p in /nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-ripgrep-1.0 /nix/store/cccccccccccccccccccccccccccccccc-fd-1.0; do for b in "$p"/bin/*; do if [ -e "$b" ]; then ln -sf "$b" /out/usr/local/bin/; fi; done; done

FROM --platform=$BUILDPLATFORM nixos/nix:latest@sha256:nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn AS nix-arm64
ARG SOURCE_DATE_EPOCH
RUN nix --extra-experimental-features nix-command copy --from https://cache.nixos.org \
      /nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-ripgrep-1.0 \
      /nix/store/dddddddddddddddddddddddddddddddd-fd-1.0 \
 && mkdir -p /out/nix/store /out/usr/local/bin \
 && cp -a $(nix-store --query --requisites /nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-ripgrep-1.0 /nix/store/dddddddddddddddddddddddddddddddd-fd-1.0) /out/nix/store/ \
 && for p in /nix/store/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb-ripgrep-1.0 /nix/store/dddddddddddddddddddddddddddddddd-fd-1.0; do for b in "$p"/bin/*; do if [ -e "$b" ]; then ln -sf "$b" /out/usr/local/bin/; fi; done; done

FROM nix-${TARGETARCH} AS nix

# ---- image ----
# packages: dnf (fedora-44)
FROM scratch AS pkgs-amd64
ADD --checksum=sha256:9999999999999999999999999999999999999999999999999999999999999999 https://kojipkgs.fedoraproject.org/packages/jq/1.8.1/3.fc44/jq_1.7.1_amd64.rpm /pkgs/jq_1.7.1_amd64.rpm

FROM debian:trixie-slim@sha256:0000000000000000000000000000000000000000000000000000000000000000 AS packages-amd64
ARG SOURCE_DATE_EPOCH
RUN --mount=type=bind,from=pkgs-amd64,source=/pkgs,target=/tmp/factory-pkgs <<'FACTORY_EOF'
set -eu
rpm -Uvh --quiet /tmp/factory-pkgs/*.rpm
rm -rf /var/cache/ldconfig/aux-cache
first=$(ls /tmp/factory-pkgs/*.rpm | head -n 1)
tid=$(rpm -q --qf '%{INSTALLTID}\n' "$(rpm -qp --nosignature --qf '%{NAME}' "$first")" | head -n 1)
for d in /usr/lib/sysimage/rpm /var/lib/rpm; do
  db="$d/rpmdb.sqlite"
  [ -f "$db" ] && [ ! -L "$d" ] || continue
  if [ -n "${SOURCE_DATE_EPOCH:-}" ] && [ "$tid" != "$SOURCE_DATE_EPOCH" ]; then
    python3 - "$db" "$tid" "$SOURCE_DATE_EPOCH" <<'PY'
import sqlite3, struct, sys
db, old, new = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
INSTALLTIME, INSTALLTID, INT32 = 1008, 1128, 4
c = sqlite3.connect(db)
for hnum, blob in c.execute("SELECT hnum, blob FROM Packages").fetchall():
    b = bytearray(blob)
    il = struct.unpack(">I", b[:4])[0]
    data, pos = 8 + il * 16, {}
    for i in range(il):
        tag, typ, off, cnt = struct.unpack(">IIII", b[8 + i * 16:24 + i * 16])
        if tag in (INSTALLTIME, INSTALLTID) and typ == INT32 and cnt == 1:
            pos[tag] = data + off
    if INSTALLTID in pos and struct.unpack(">I", b[pos[INSTALLTID]:pos[INSTALLTID] + 4])[0] == old:
        for p in pos.values():
            b[p:p + 4] = struct.pack(">I", new)
        c.execute("UPDATE Packages SET blob = ? WHERE hnum = ?", (bytes(b), hnum))
c.execute("UPDATE Installtid SET key = ? WHERE key = ?", (struct.pack("<I", new), struct.pack("<I", old)))
c.commit()
c.execute("PRAGMA wal_checkpoint(TRUNCATE)")
c.close()
PY
  fi
  if [ ! -s "$db-wal" ]; then rm -f "$db-wal" "$db-shm"; fi
done
FACTORY_EOF

FROM scratch AS pkgs-arm64
ADD --checksum=sha256:9999999999999999999999999999999999999999999999999999999999999999 https://kojipkgs.fedoraproject.org/packages/jq/1.8.1/3.fc44/jq_1.7.1_arm64.rpm /pkgs/jq_1.7.1_arm64.rpm

FROM debian:trixie-slim@sha256:0000000000000000000000000000000000000000000000000000000000000000 AS packages-arm64
ARG SOURCE_DATE_EPOCH
RUN --mount=type=bind,from=pkgs-arm64,source=/pkgs,target=/tmp/factory-pkgs <<'FACTORY_EOF'
set -eu
rpm -Uvh --quiet /tmp/factory-pkgs/*.rpm
rm -rf /var/cache/ldconfig/aux-cache
first=$(ls /tmp/factory-pkgs/*.rpm | head -n 1)
tid=$(rpm -q --qf '%{INSTALLTID}\n' "$(rpm -qp --nosignature --qf '%{NAME}' "$first")" | head -n 1)
for d in /usr/lib/sysimage/rpm /var/lib/rpm; do
  db="$d/rpmdb.sqlite"
  [ -f "$db" ] && [ ! -L "$d" ] || continue
  if [ -n "${SOURCE_DATE_EPOCH:-}" ] && [ "$tid" != "$SOURCE_DATE_EPOCH" ]; then
    python3 - "$db" "$tid" "$SOURCE_DATE_EPOCH" <<'PY'
import sqlite3, struct, sys
db, old, new = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
INSTALLTIME, INSTALLTID, INT32 = 1008, 1128, 4
c = sqlite3.connect(db)
for hnum, blob in c.execute("SELECT hnum, blob FROM Packages").fetchall():
    b = bytearray(blob)
    il = struct.unpack(">I", b[:4])[0]
    data, pos = 8 + il * 16, {}
    for i in range(il):
        tag, typ, off, cnt = struct.unpack(">IIII", b[8 + i * 16:24 + i * 16])
        if tag in (INSTALLTIME, INSTALLTID) and typ == INT32 and cnt == 1:
            pos[tag] = data + off
    if INSTALLTID in pos and struct.unpack(">I", b[pos[INSTALLTID]:pos[INSTALLTID] + 4])[0] == old:
        for p in pos.values():
            b[p:p + 4] = struct.pack(">I", new)
        c.execute("UPDATE Packages SET blob = ? WHERE hnum = ?", (bytes(b), hnum))
c.execute("UPDATE Installtid SET key = ? WHERE key = ?", (struct.pack("<I", new), struct.pack("<I", old)))
c.commit()
c.execute("PRAGMA wal_checkpoint(TRUNCATE)")
c.close()
PY
  fi
  if [ ! -s "$db-wal" ]; then rm -f "$db-wal" "$db-shm"; fi
done
FACTORY_EOF

FROM packages-${TARGETARCH}
COPY --link --from=nix /out/ /
