# syntax=docker/dockerfile:1@sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
#
# Code generated by factory from image.yaml and image.lock.yaml. DO NOT EDIT.
# Image: registry.example/demo
#
# Rebuild bit-for-bit with `factory verify`, or directly with BuildKit
# (moby/buildkit:v0.33.1@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb):
#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \
#     --opt platform=linux/amd64,linux/arm64 \
#     --opt build-arg:SOURCE_DATE_EPOCH=1700000000 \
#     --output type=oci,dest=image.tar,rewrite-timestamp=true
# from a context staged with `factory render --context-dir`.

ARG TARGETARCH

# ---- tool: helm (url 4.3.0, verified: checksum-file) ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt AS tool-helm-amd64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:1111111111111111111111111111111111111111111111111111111111111111 https://get.helm.sh/helm-amd64.tar.gz /src/helm-amd64.tar.gz
RUN mkdir -p /x && tar -xzf /src/helm-amd64.tar.gz -C /x \
 && install -D -m 0755 /x/linux-amd64/helm /out/usr/local/bin/helm

FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt AS tool-helm-arm64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:2222222222222222222222222222222222222222222222222222222222222222 https://get.helm.sh/helm-arm64.tar.gz /src/helm-arm64.tar.gz
RUN mkdir -p /x && tar -xzf /src/helm-arm64.tar.gz -C /x \
 && install -D -m 0755 /x/linux-arm64/helm /out/usr/local/bin/helm

FROM tool-helm-${TARGETARCH} AS tool-helm

# ---- tool: script (url, verified: checksum-file) ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt AS tool-script
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa https://example.com/install.sh /src/install.sh
RUN install -D -m 0644 /src/install.sh /out/opt/install.sh

# ---- tool: crane (oci, verified: image-digest) ----
# copied straight from gcr.io/go-containerregistry/crane:latest@sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

# ---- tool: yq (go v4.54.1, verified: go-sumdb) ----
FROM --platform=$BUILDPLATFORM golang:1@sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc AS tool-yq
ARG TARGETOS TARGETARCH SOURCE_DATE_EPOCH
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH GOFLAGS=-trimpath \
    go install -ldflags='-s -w -buildid=' github.com/mikefarah/yq/v4@v4.54.1 \
 && install -D -m 0755 "$(find /go/bin -type f | head -n 1)" /out/usr/local/bin/yq

# ---- tool: awscli (build, verified: unverified) ----
# runs on the target platform; everything written to /out is copied into the image
FROM python:3@sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc AS tool-awscli
ARG SOURCE_DATE_EPOCH
RUN <<'FACTORY_EOF'
set -eu
mkdir -p /out
pip install --prefix=/out/usr/local awscli==2.0.0
FACTORY_EOF

# ---- files ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt AS files
ARG SOURCE_DATE_EPOCH
COPY files/0/ /in/0/
COPY ["files/1/hello world.sh","/in/1/hello world.sh"]
RUN mkdir -p /out/etc/demo && cp -R /in/0/. /out/etc/demo/ \
 && install -D -m 0755 '/in/1/hello world.sh' '/out/usr/local/bin/hello world.sh'

# ---- image ----
FROM cgr.dev/chainguard/wolfi-base:latest@sha256:0000000000000000000000000000000000000000000000000000000000000000 AS packages-amd64
ARG SOURCE_DATE_EPOCH
RUN apk add --no-cache --repositories-file /dev/null \
      --repository https://apk.cgr.dev/chainguard \
      jq=1.8.2-r2 \
      oniguruma=6.9.10-r5 \
 && rm -f /var/cache/ldconfig/aux-cache

FROM cgr.dev/chainguard/wolfi-base:latest@sha256:0000000000000000000000000000000000000000000000000000000000000000 AS packages-arm64
ARG SOURCE_DATE_EPOCH
RUN apk add --no-cache --repositories-file /dev/null \
      --repository https://apk.cgr.dev/chainguard \
      jq=1.8.2-r1 \
      oniguruma=6.9.10-r5 \
 && rm -f /var/cache/ldconfig/aux-cache

FROM packages-${TARGETARCH}
COPY --link --from=tool-helm /out/ /
COPY --link --from=tool-script /out/ /
COPY --link --from=gcr.io/go-containerregistry/crane:latest@sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc /ko-app/crane /usr/local/bin/crane
COPY --link --from=tool-yq /out/ /
COPY --link --from=tool-awscli /out/ /
COPY --link --from=files /out/ /
ENV A="1"
ENV B="say \"\$HI\""
LABEL "org.opencontainers.image.source"="https://example.com"
USER 65532
ENTRYPOINT ["/bin/sh","-c","a && b <c>"]
