# syntax=docker/dockerfile:1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e
#
# Code generated by factory from image.yaml and image.lock.yaml. DO NOT EDIT.
# Image: ghcr.io/northcutted/images/debian-tools
#
# Rebuild bit-for-bit with `factory verify`, or directly with BuildKit
# (moby/buildkit:v0.33.1@sha256:cec9f139f45e93c5c69c60f8b07cfad9f43f4ef6b6a6cd917527fea5ff2e3dea):
#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \
#     --opt platform=linux/amd64,linux/arm64 \
#     --opt build-arg:SOURCE_DATE_EPOCH=1790899200 \
#     --output type=oci,dest=image.tar,rewrite-timestamp=true
# from a context staged with `factory render --context-dir`.

ARG TARGETARCH

# ---- nix: ripgrep 15.1.0 (verified: nix-signature) ----
FROM --platform=$BUILDPLATFORM nixos/nix:latest@sha256:7a007c766426c1877758ddc5cb87a965ac131fc78c582ce0083d922d51ae945c AS nix-amd64
ARG SOURCE_DATE_EPOCH
RUN nix --extra-experimental-features nix-command copy --from https://cache.nixos.org \
      /nix/store/6jwbzg6fwjyla5y772iycsgriz4azgil-ripgrep-15.1.0 \
 && mkdir -p /out/nix/store /out/usr/local/bin \
 && cp -a $(nix-store --query --requisites /nix/store/6jwbzg6fwjyla5y772iycsgriz4azgil-ripgrep-15.1.0) /out/nix/store/ \
 && for p in /nix/store/6jwbzg6fwjyla5y772iycsgriz4azgil-ripgrep-15.1.0; do for b in "$p"/bin/*; do if [ -e "$b" ]; then ln -sf "$b" /out/usr/local/bin/; fi; done; done

FROM --platform=$BUILDPLATFORM nixos/nix:latest@sha256:7a007c766426c1877758ddc5cb87a965ac131fc78c582ce0083d922d51ae945c AS nix-arm64
ARG SOURCE_DATE_EPOCH
RUN nix --extra-experimental-features nix-command copy --from https://cache.nixos.org \
      /nix/store/8ffg6c7ak5njp6hwbqzg23g39wlhnvn8-ripgrep-15.1.0 \
 && mkdir -p /out/nix/store /out/usr/local/bin \
 && cp -a $(nix-store --query --requisites /nix/store/8ffg6c7ak5njp6hwbqzg23g39wlhnvn8-ripgrep-15.1.0) /out/nix/store/ \
 && for p in /nix/store/8ffg6c7ak5njp6hwbqzg23g39wlhnvn8-ripgrep-15.1.0; do for b in "$p"/bin/*; do if [ -e "$b" ]; then ln -sf "$b" /out/usr/local/bin/; fi; done; done

FROM nix-${TARGETARCH} AS nix

# ---- tool: kubectl (url 1.37.1, verified: checksum-file) ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-kubectl-amd64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:65691ff77eb6fa44c908b77a1082c9f092c3b9733b5cefabec0d1104890e21a8 https://dl.k8s.io/release/v1.37.1/bin/linux/amd64/kubectl /src/kubectl
RUN install -D -m 0755 /src/kubectl /out/usr/local/bin/kubectl

FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-kubectl-arm64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:ff749f4b78d9c4f1ec87307df9b50119ed819e2094aa9810cb9acffc3286c8c7 https://dl.k8s.io/release/v1.37.1/bin/linux/arm64/kubectl /src/kubectl
RUN install -D -m 0755 /src/kubectl /out/usr/local/bin/kubectl

FROM tool-kubectl-${TARGETARCH} AS tool-kubectl

# ---- image ----
# packages: apt (debian-13, snapshot 20261003T224053Z)
FROM scratch AS pkgs-amd64
ADD --checksum=sha256:ef590f89563aa4b46c8260d49d1cea0fc1b181d19e8df3782694706adf05c184 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/ca-certificates/ca-certificates_20250419_all.deb /pkgs/ca-certificates_20250419_all.deb
ADD --checksum=sha256:ebb7e0cbe30ad23bce0d28a848ccfeb9b73b82817eb4fe12fa20d2845f62dc73 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/curl/curl_8.14.1-2%2bdeb13u5_amd64.deb /pkgs/curl_8.14.1-2+deb13u5_amd64.deb
ADD --checksum=sha256:3e35662fd5c46add561703e54031a1d8ad9df45811927689f0a51122b13be722 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/git/git_2.47.3-0%2bdeb13u1_amd64.deb /pkgs/git_2.47.3-0+deb13u1_amd64.deb
ADD --checksum=sha256:b58306b60e1dff920e1e18bc7e1e499f2ef75184190ab3d98657b165969bf7c9 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/git/git-man_2.47.3-0%2bdeb13u1_all.deb /pkgs/git-man_2.47.3-0+deb13u1_all.deb
ADD --checksum=sha256:7350392f700e20e46b7ae174a57f54e4ea106dd559753646d629b4e618bf2bff https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/j/jq/jq_1.7.1-6%2bdeb13u4_amd64.deb /pkgs/jq_1.7.1-6+deb13u4_amd64.deb
ADD --checksum=sha256:0fb79f88db210afbd69282ab9649e525f393ec6950ca34da1a6b359250b8d7db https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/b/brotli/libbrotli1_1.1.0-2%2bb7_amd64.deb /pkgs/libbrotli1_1.1.0-2+b7_amd64.deb
ADD --checksum=sha256:bd43e020b8fed399db3eebf098111f10fba4c436fff99ccad72cc7e27c9764ec https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/e/e2fsprogs/libcom-err2_1.47.2-3%2bb12_amd64.deb /pkgs/libcom-err2_1.47.2-3+b12_amd64.deb
ADD --checksum=sha256:19da93544615a4c9a3d7df473f5bf8ebca99442454622e9b0460168dadf7b8ae https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/curl/libcurl3t64-gnutls_8.14.1-2%2bdeb13u5_amd64.deb /pkgs/libcurl3t64-gnutls_8.14.1-2+deb13u5_amd64.deb
ADD --checksum=sha256:0dedddfe614fc4a4335c9167b73c64a50136edd76b7991aa851408d0795163eb https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/curl/libcurl4t64_8.14.1-2%2bdeb13u5_amd64.deb /pkgs/libcurl4t64_8.14.1-2+deb13u5_amd64.deb
ADD --checksum=sha256:06110a972bdc52f6c6d6615dddbe97f836c61d0e36c685ef4107c2eaa81f871f https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libe/liberror-perl/liberror-perl_0.17030-1_all.deb /pkgs/liberror-perl_0.17030-1_all.deb
ADD --checksum=sha256:38abe0e710a07688e9c149d74536e67cfee0364bdb64dd6d644c32a1cfad389f https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/e/expat/libexpat1_2.8.3-1%7edeb13u1_amd64.deb /pkgs/libexpat1_2.8.3-1~deb13u1_amd64.deb
ADD --checksum=sha256:0ebdc340de33333639c3c63874cd4b15ac2e83dfa1ef3053b7eefaf4919f4f68 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libf/libffi/libffi8_3.4.8-2_amd64.deb /pkgs/libffi8_3.4.8-2_amd64.deb
ADD --checksum=sha256:2cbd43cf2dfbf57ff48188b5d79d29cf7ea8f0dedaa61ab0bcc02eceff50ea01 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/gdbm/libgdbm-compat4t64_1.24-2_amd64.deb /pkgs/libgdbm-compat4t64_1.24-2_amd64.deb
ADD --checksum=sha256:e7b42c68c391e278733adb3c1efdacd24d660862bd7bac0efbc10a91e5696dfc https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/gdbm/libgdbm6t64_1.24-2_amd64.deb /pkgs/libgdbm6t64_1.24-2_amd64.deb
ADD --checksum=sha256:18a8bdfd91c7e3bcb01719d55a2b56849c7160b34f1f52b1c4fdfdd41bf1352b https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/gnutls28/libgnutls30t64_3.8.9-3%2bdeb13u4_amd64.deb /pkgs/libgnutls30t64_3.8.9-3+deb13u4_amd64.deb
ADD --checksum=sha256:30847c1fde4240567d7ed3aeab4f655dd591203758b857e85e824045aae70299 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/krb5/libgssapi-krb5-2_1.21.3-5%2bdeb13u1_amd64.deb /pkgs/libgssapi-krb5-2_1.21.3-5+deb13u1_amd64.deb
ADD --checksum=sha256:90b039bcdc4578f8e1c4935adf8dbb525e36a164deefdbbb8c45bac347d48278 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libi/libidn2/libidn2-0_2.3.8-2_amd64.deb /pkgs/libidn2-0_2.3.8-2_amd64.deb
ADD --checksum=sha256:70bb2cbd66d5ada4349067ae9f61d0560b3b359d4203f2c051ca5773153ae0ba https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/j/jq/libjq1_1.7.1-6%2bdeb13u4_amd64.deb /pkgs/libjq1_1.7.1-6+deb13u4_amd64.deb
ADD --checksum=sha256:7da07ee674b47f1f0be7cc89317c25310086a1f1761217d0f72e6ae2c5a69b84 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/krb5/libk5crypto3_1.21.3-5%2bdeb13u1_amd64.deb /pkgs/libk5crypto3_1.21.3-5+deb13u1_amd64.deb
ADD --checksum=sha256:0b11ad17be0300b63ad4eeb4c6450fed24d34b7b740f23e5363dcb29ee6d5eba https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/keyutils/libkeyutils1_1.6.3-6_amd64.deb /pkgs/libkeyutils1_1.6.3-6_amd64.deb
ADD --checksum=sha256:47d71d6a7f2e59b9bae5f89602397594805113b95889ad18fa703cd53abafc97 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/krb5/libkrb5-3_1.21.3-5%2bdeb13u1_amd64.deb /pkgs/libkrb5-3_1.21.3-5+deb13u1_amd64.deb
ADD --checksum=sha256:3a0acd8b37955c0e102c756b52c97df2a31f67b96453c35dab70df218d309117 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/krb5/libkrb5support0_1.21.3-5%2bdeb13u1_amd64.deb /pkgs/libkrb5support0_1.21.3-5+deb13u1_amd64.deb
ADD --checksum=sha256:60069e4a550ca890113fa89d3001417781b18e146ec5d637d31e368dec9909bd https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/o/openldap/libldap2_2.6.10%2bdfsg-1_amd64.deb /pkgs/libldap2_2.6.10+dfsg-1_amd64.deb
ADD --checksum=sha256:896cb217537c09251fb909b8541349010ac279d802d871e98c06a62a2c67ce2c https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/n/nghttp2/libnghttp2-14_1.64.0-1.1%2bdeb13u1_amd64.deb /pkgs/libnghttp2-14_1.64.0-1.1+deb13u1_amd64.deb
ADD --checksum=sha256:388e4c33b72829cbf0d098afdc8539fa5ba7458eddb077f5538fdb4d5538716b https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/n/nghttp3/libnghttp3-9_1.8.0-1_amd64.deb /pkgs/libnghttp3-9_1.8.0-1_amd64.deb
ADD --checksum=sha256:627eec81ebbd48c4e6091f5cd9dc5070b792b7075000eed60ab08c7daa961caf https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/n/ngtcp2/libngtcp2-16_1.11.0-1%2bdeb13u1_amd64.deb /pkgs/libngtcp2-16_1.11.0-1+deb13u1_amd64.deb
ADD --checksum=sha256:2a7f109c0c4db6a800e4661c5e5e34e1f1f83c8162482276183d1ada9da7c96c https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/n/ngtcp2/libngtcp2-crypto-gnutls8_1.11.0-1%2bdeb13u1_amd64.deb /pkgs/libngtcp2-crypto-gnutls8_1.11.0-1+deb13u1_amd64.deb
ADD --checksum=sha256:3abee130696244050500bcc7870e3b4cb82ddd87149ece3fd55010c3d4e1d18c https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libo/libonig/libonig5_6.9.9-1%2bb1_amd64.deb /pkgs/libonig5_6.9.9-1+b1_amd64.deb
ADD --checksum=sha256:784bf2063e166c8bc851a32623b74ebd85c499043a9d57c5bbd64fa63447f45a https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/p/p11-kit/libp11-kit0_0.25.5-3_amd64.deb /pkgs/libp11-kit0_0.25.5-3_amd64.deb
ADD --checksum=sha256:e44777ff47ad248d1debd57e1f96ab5e89061a341008ae39880ba3b5fc15f273 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/p/perl/libperl5.40_5.40.1-6%2bdeb13u1_amd64.deb /pkgs/libperl5.40_5.40.1-6+deb13u1_amd64.deb
ADD --checksum=sha256:59d42bb1f9ebc0d1776fe616efb08a7a8568b05982e00f70b03c63863db768ab https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libp/libpsl/libpsl5t64_0.21.2-1.1%2bb1_amd64.deb /pkgs/libpsl5t64_0.21.2-1.1+b1_amd64.deb
ADD --checksum=sha256:93baa2004cbe6c8721b9e81beed078612540aef120970b4751305c51c6697368 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/r/rtmpdump/librtmp1_2.4%2b20151223.gitfa8646d.1-2%2bb5_amd64.deb /pkgs/librtmp1_2.4+20151223.gitfa8646d.1-2+b5_amd64.deb
ADD --checksum=sha256:66e49d7ae026811b49a0050f18b0325960a2625ffd1ff60d91b7844a815fa9d2 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.28%2bdfsg1-9_amd64.deb /pkgs/libsasl2-2_2.1.28+dfsg1-9_amd64.deb
ADD --checksum=sha256:a5c38659fbd62c33c6d9bfa2be43e75a572d1818531aad32dd74d0a58cc4bd19 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/cyrus-sasl2/libsasl2-modules-db_2.1.28%2bdfsg1-9_amd64.deb /pkgs/libsasl2-modules-db_2.1.28+dfsg1-9_amd64.deb
ADD --checksum=sha256:dbb1024c192d4d292b7cfa902b96076cfe81b56a5eed4fb28da36e8bf543e49a https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libs/libssh2/libssh2-1t64_1.11.1-1%2bdeb13u2_amd64.deb /pkgs/libssh2-1t64_1.11.1-1+deb13u2_amd64.deb
ADD --checksum=sha256:ff16bc048bcd7d1b256094450b79c77947d8e76fe2a24bd99b91021d591fa074 https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/o/openssl/libssl3t64_3.5.7-1%7edeb13u3_amd64.deb /pkgs/libssl3t64_3.5.7-1~deb13u3_amd64.deb
ADD --checksum=sha256:23fec6e06583ce2bad9b2c04c9b485e90440e259b1abf8677cd80d3ce60831ad https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libt/libtasn1-6/libtasn1-6_4.20.0-2%2bdeb13u1_amd64.deb /pkgs/libtasn1-6_4.20.0-2+deb13u1_amd64.deb
ADD --checksum=sha256:6dd3490bef06ea1096f32d10766b7e016cf579bfae8451d1b7df15ce05b8aa46 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libu/libunistring/libunistring5_1.3-2_amd64.deb /pkgs/libunistring5_1.3-2_amd64.deb
ADD --checksum=sha256:43a9cbcf2a8a0e1f0a1c3f5a33ee1f56b269690e7a2129f2b2d0582e789589d7 https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/o/openssl/openssl_3.5.7-1%7edeb13u3_amd64.deb /pkgs/openssl_3.5.7-1~deb13u3_amd64.deb
ADD --checksum=sha256:c12e0266c4780749a4702b8959ac979689f4182e18eed85a8a5eb90ed0e16eab https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/o/openssl/openssl-provider-legacy_3.5.7-1%7edeb13u3_amd64.deb /pkgs/openssl-provider-legacy_3.5.7-1~deb13u3_amd64.deb
ADD --checksum=sha256:ef145c247787d6f40dcdefd5b417502484827cde0d555998c17fd5b27ec1e1dd https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/p/perl/perl_5.40.1-6%2bdeb13u1_amd64.deb /pkgs/perl_5.40.1-6+deb13u1_amd64.deb
ADD --checksum=sha256:4c46cdd8f3135aa1c95f07e817f8e5d9be590687441ac1c27e3a8c49400f35ce https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/p/perl/perl-modules-5.40_5.40.1-6%2bdeb13u1_all.deb /pkgs/perl-modules-5.40_5.40.1-6+deb13u1_all.deb

FROM debian:trixie-slim@sha256:a99cfc517144bc59b1978475ec53b46ecabec7e43635402ee5b77cc54cd1b20a AS packages-amd64
ARG SOURCE_DATE_EPOCH
RUN --mount=type=bind,from=pkgs-amd64,source=/pkgs,target=/tmp/factory-pkgs \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends /tmp/factory-pkgs/*.deb \
 && rm -rf /var/lib/apt/lists/* /var/cache/apt/*.bin /var/log/apt/* /var/log/dpkg.log /var/log/alternatives.log /var/cache/ldconfig/aux-cache /var/cache/debconf/*-old /var/lib/dpkg/*-old

FROM scratch AS pkgs-arm64
ADD --checksum=sha256:ef590f89563aa4b46c8260d49d1cea0fc1b181d19e8df3782694706adf05c184 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/ca-certificates/ca-certificates_20250419_all.deb /pkgs/ca-certificates_20250419_all.deb
ADD --checksum=sha256:3ea9ea868ffaddb2aba840b52dcd1e59b74dbe625f0c4c4e2458c9d01bc03e6f https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/curl/curl_8.14.1-2%2bdeb13u5_arm64.deb /pkgs/curl_8.14.1-2+deb13u5_arm64.deb
ADD --checksum=sha256:8c6b1e96b226211260d7814472215a8a1ed38ee37400c421d454391c1807cb5a https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/git/git_2.47.3-0%2bdeb13u1_arm64.deb /pkgs/git_2.47.3-0+deb13u1_arm64.deb
ADD --checksum=sha256:b58306b60e1dff920e1e18bc7e1e499f2ef75184190ab3d98657b165969bf7c9 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/git/git-man_2.47.3-0%2bdeb13u1_all.deb /pkgs/git-man_2.47.3-0+deb13u1_all.deb
ADD --checksum=sha256:5d77ae282441d3ef0560141d55b4ac562d2cba7a873eb9ad7572ccfe69471ebf https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/j/jq/jq_1.7.1-6%2bdeb13u4_arm64.deb /pkgs/jq_1.7.1-6+deb13u4_arm64.deb
ADD --checksum=sha256:10270398c4842e71c72b4081fa1761728b3225d6c8dce7c58d5baafe58a5e18f https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/b/brotli/libbrotli1_1.1.0-2%2bb7_arm64.deb /pkgs/libbrotli1_1.1.0-2+b7_arm64.deb
ADD --checksum=sha256:1acba7e14a17a3f4b8008454e1a75840a5cdff4259d3c1d369092d82089ea0d8 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/e/e2fsprogs/libcom-err2_1.47.2-3%2bb12_arm64.deb /pkgs/libcom-err2_1.47.2-3+b12_arm64.deb
ADD --checksum=sha256:e7907dba88227fa61f86e1e3ea198c770cb0a255d506f31d9564278dfba3c898 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/curl/libcurl3t64-gnutls_8.14.1-2%2bdeb13u5_arm64.deb /pkgs/libcurl3t64-gnutls_8.14.1-2+deb13u5_arm64.deb
ADD --checksum=sha256:af72e1cd69240a42a76a578e6902b65f9fa641f5e7352e4bfa0ec5aa38d25204 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/curl/libcurl4t64_8.14.1-2%2bdeb13u5_arm64.deb /pkgs/libcurl4t64_8.14.1-2+deb13u5_arm64.deb
ADD --checksum=sha256:06110a972bdc52f6c6d6615dddbe97f836c61d0e36c685ef4107c2eaa81f871f https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libe/liberror-perl/liberror-perl_0.17030-1_all.deb /pkgs/liberror-perl_0.17030-1_all.deb
ADD --checksum=sha256:c3248c4beb721c8290e6e34527ae56b1fc965aa6a14982ca602df4458ef0854e https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/e/expat/libexpat1_2.8.3-1%7edeb13u1_arm64.deb /pkgs/libexpat1_2.8.3-1~deb13u1_arm64.deb
ADD --checksum=sha256:d84a783b818f2386627604e64b793eb4ac5bb9ea1ba321a194a1c9c82fe09a01 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libf/libffi/libffi8_3.4.8-2_arm64.deb /pkgs/libffi8_3.4.8-2_arm64.deb
ADD --checksum=sha256:266b9a9e8d1ecc4393ebd29bec7e7c0fe1505b1d8755033af9e15df161316627 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/gdbm/libgdbm-compat4t64_1.24-2_arm64.deb /pkgs/libgdbm-compat4t64_1.24-2_arm64.deb
ADD --checksum=sha256:329efe726e24a413b9933e298ce24d255973ec111eea0ca721157968fd24156a https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/gdbm/libgdbm6t64_1.24-2_arm64.deb /pkgs/libgdbm6t64_1.24-2_arm64.deb
ADD --checksum=sha256:337ef41ab360015d051d6a07f85f8aa6706b35712e3dea23157eba9c902196e2 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/g/gnutls28/libgnutls30t64_3.8.9-3%2bdeb13u4_arm64.deb /pkgs/libgnutls30t64_3.8.9-3+deb13u4_arm64.deb
ADD --checksum=sha256:70803e8f5b9dd0a7167671bdd0b3cd05642384c1fc49e8270d340d85bf6c7d4c https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/krb5/libgssapi-krb5-2_1.21.3-5%2bdeb13u1_arm64.deb /pkgs/libgssapi-krb5-2_1.21.3-5+deb13u1_arm64.deb
ADD --checksum=sha256:d2e5cef812f15db1eeb35f0a193158ee102a9e94284036c0e293521f2761d2d7 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libi/libidn2/libidn2-0_2.3.8-2_arm64.deb /pkgs/libidn2-0_2.3.8-2_arm64.deb
ADD --checksum=sha256:400a7367f8acf48d48776a877a8d08b237804546ab598affd0fe15e6e7ab84e5 https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/j/jq/libjq1_1.7.1-6%2bdeb13u4_arm64.deb /pkgs/libjq1_1.7.1-6+deb13u4_arm64.deb
ADD --checksum=sha256:2453e8d4fa3b91b868d5bc10e84a15ad9c7bc4e4cb49379cb1f560bdce50db4a https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/krb5/libk5crypto3_1.21.3-5%2bdeb13u1_arm64.deb /pkgs/libk5crypto3_1.21.3-5+deb13u1_arm64.deb
ADD --checksum=sha256:5e680f317a6613161986417fb3ed63007c9228343f5ac2348551b103cc7fd7b4 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/keyutils/libkeyutils1_1.6.3-6_arm64.deb /pkgs/libkeyutils1_1.6.3-6_arm64.deb
ADD --checksum=sha256:1f5c46480abf894f662d894696c8a6c6510c2b20616cd453e88b27b11d3be25d https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/krb5/libkrb5-3_1.21.3-5%2bdeb13u1_arm64.deb /pkgs/libkrb5-3_1.21.3-5+deb13u1_arm64.deb
ADD --checksum=sha256:6381bcb54e58854f9ebac2dfa580c3d6112d01b4ca3f725e7263b9374f79608e https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/k/krb5/libkrb5support0_1.21.3-5%2bdeb13u1_arm64.deb /pkgs/libkrb5support0_1.21.3-5+deb13u1_arm64.deb
ADD --checksum=sha256:38fae6af20d41e4b0a8ea1b96d0b81a7a5551a61595bc866c9af870eadfdf1bd https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/o/openldap/libldap2_2.6.10%2bdfsg-1_arm64.deb /pkgs/libldap2_2.6.10+dfsg-1_arm64.deb
ADD --checksum=sha256:ca222b98d5bef2193c05a1e736d0619798ba7a8f8e92526f3e1d06edcd0bf751 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/n/nghttp2/libnghttp2-14_1.64.0-1.1%2bdeb13u1_arm64.deb /pkgs/libnghttp2-14_1.64.0-1.1+deb13u1_arm64.deb
ADD --checksum=sha256:26bfb8d1bead043f57d95663bab02f7611e7078fb7cf71383fa480c4b4c24d81 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/n/nghttp3/libnghttp3-9_1.8.0-1_arm64.deb /pkgs/libnghttp3-9_1.8.0-1_arm64.deb
ADD --checksum=sha256:1ced2874229e4a503060c244730baf75e61b1d5444472b10e5022f1594f4ab88 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/n/ngtcp2/libngtcp2-16_1.11.0-1%2bdeb13u1_arm64.deb /pkgs/libngtcp2-16_1.11.0-1+deb13u1_arm64.deb
ADD --checksum=sha256:4a220245385ec7222f4a20e444532808b90139b70ea9c7eeab179c927a27b37f https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/n/ngtcp2/libngtcp2-crypto-gnutls8_1.11.0-1%2bdeb13u1_arm64.deb /pkgs/libngtcp2-crypto-gnutls8_1.11.0-1+deb13u1_arm64.deb
ADD --checksum=sha256:137e708575c0622d347815d19cb471a107546b16e9602805ee27afad7bba107f https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libo/libonig/libonig5_6.9.9-1%2bb1_arm64.deb /pkgs/libonig5_6.9.9-1+b1_arm64.deb
ADD --checksum=sha256:78bfc746e68a5217e845f488f69100ed89d10c8886fbd3ffce937acb6a7d88fb https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/p/p11-kit/libp11-kit0_0.25.5-3_arm64.deb /pkgs/libp11-kit0_0.25.5-3_arm64.deb
ADD --checksum=sha256:b3cf688efb6096b2f3d95e96ad5b216602146ad11f792c1f3b2f66b5556241d9 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/p/perl/libperl5.40_5.40.1-6%2bdeb13u1_arm64.deb /pkgs/libperl5.40_5.40.1-6+deb13u1_arm64.deb
ADD --checksum=sha256:7ea03d8a7d16edce7b1b1e94980c058c0f1fb3c595eb9154b0e8590d0e7f75af https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libp/libpsl/libpsl5t64_0.21.2-1.1%2bb1_arm64.deb /pkgs/libpsl5t64_0.21.2-1.1+b1_arm64.deb
ADD --checksum=sha256:20d52d20c4834158e956ae8e1d42a61d22330062052116d5422daa2d3b1d433b https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/r/rtmpdump/librtmp1_2.4%2b20151223.gitfa8646d.1-2%2bb5_arm64.deb /pkgs/librtmp1_2.4+20151223.gitfa8646d.1-2+b5_arm64.deb
ADD --checksum=sha256:6431628c62524c8397255c1c4a7c7ef63661b801f3be9a59ad41e7a2e46e6210 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.28%2bdfsg1-9_arm64.deb /pkgs/libsasl2-2_2.1.28+dfsg1-9_arm64.deb
ADD --checksum=sha256:ed6eb05f8ded71ab16a0369845805b373fc8a71c0e7d33f73fa2fb11e83a1977 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/c/cyrus-sasl2/libsasl2-modules-db_2.1.28%2bdfsg1-9_arm64.deb /pkgs/libsasl2-modules-db_2.1.28+dfsg1-9_arm64.deb
ADD --checksum=sha256:245565f4ce5493d67a3c54e26bc3d9cf28b1b70eeb912de7cda61af52268017d https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libs/libssh2/libssh2-1t64_1.11.1-1%2bdeb13u2_arm64.deb /pkgs/libssh2-1t64_1.11.1-1+deb13u2_arm64.deb
ADD --checksum=sha256:d0681293a160392186c6ef85a165e40603d1628a099936137d24d391bd591f97 https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/o/openssl/libssl3t64_3.5.7-1%7edeb13u3_arm64.deb /pkgs/libssl3t64_3.5.7-1~deb13u3_arm64.deb
ADD --checksum=sha256:e421da949cd26245f24c594265d6a01900b5e060e80793f68b977f7bfaa009ef https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libt/libtasn1-6/libtasn1-6_4.20.0-2%2bdeb13u1_arm64.deb /pkgs/libtasn1-6_4.20.0-2+deb13u1_arm64.deb
ADD --checksum=sha256:4847467a0e47039837895e88f5a99a4a86a3d8266be40c3c896fc7c10d552dc7 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/libu/libunistring/libunistring5_1.3-2_arm64.deb /pkgs/libunistring5_1.3-2_arm64.deb
ADD --checksum=sha256:68f226057a7a1c1f23e2ffde0075ea16e27e646d829c8d3c63414c49b839c258 https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/o/openssl/openssl_3.5.7-1%7edeb13u3_arm64.deb /pkgs/openssl_3.5.7-1~deb13u3_arm64.deb
ADD --checksum=sha256:dae4ab96be3a1fc8fd490bbeb3938ecd102d360555d4af8ee2728b42ce9f1059 https://snapshot.debian.org/archive/debian-security/20261003T224053Z/pool/updates/main/o/openssl/openssl-provider-legacy_3.5.7-1%7edeb13u3_arm64.deb /pkgs/openssl-provider-legacy_3.5.7-1~deb13u3_arm64.deb
ADD --checksum=sha256:7f15c34267346a0da41b9fe36d509d70dfb8d39561d275c4f4c53d429290f6d2 https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/p/perl/perl_5.40.1-6%2bdeb13u1_arm64.deb /pkgs/perl_5.40.1-6+deb13u1_arm64.deb
ADD --checksum=sha256:4c46cdd8f3135aa1c95f07e817f8e5d9be590687441ac1c27e3a8c49400f35ce https://snapshot.debian.org/archive/debian/20261003T224053Z/pool/main/p/perl/perl-modules-5.40_5.40.1-6%2bdeb13u1_all.deb /pkgs/perl-modules-5.40_5.40.1-6+deb13u1_all.deb

FROM debian:trixie-slim@sha256:a99cfc517144bc59b1978475ec53b46ecabec7e43635402ee5b77cc54cd1b20a AS packages-arm64
ARG SOURCE_DATE_EPOCH
RUN --mount=type=bind,from=pkgs-arm64,source=/pkgs,target=/tmp/factory-pkgs \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends /tmp/factory-pkgs/*.deb \
 && rm -rf /var/lib/apt/lists/* /var/cache/apt/*.bin /var/log/apt/* /var/log/dpkg.log /var/log/alternatives.log /var/cache/ldconfig/aux-cache /var/cache/debconf/*-old /var/lib/dpkg/*-old

FROM packages-${TARGETARCH}
COPY --link --from=nix /out/ /
COPY --link --from=tool-kubectl /out/ /
LABEL "org.opencontainers.image.description"="Debian trixie with git, curl, jq, ripgrep, and kubectl"
LABEL "org.opencontainers.image.source"="https://github.com/northcutted/declarative-image-factory"
LABEL "org.opencontainers.image.vendor"="northcutted"
USER 65532
ENTRYPOINT ["/bin/bash"]
