# syntax=docker/dockerfile:1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e
#
# Code generated by factory from image.yaml and image.lock.yaml. DO NOT EDIT.
# Image: ghcr.io/northcutted/images/amazonlinux-tools
#
# Rebuild bit-for-bit with `clearcutt-factory verify`, or directly with BuildKit
# (moby/buildkit:v0.33.1@sha256:cec9f139f45e93c5c69c60f8b07cfad9f43f4ef6b6a6cd917527fea5ff2e3dea):
#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \
#     --opt platform=linux/amd64,linux/arm64 \
#     --opt build-arg:SOURCE_DATE_EPOCH=1791504000 \
#     --output type=oci,dest=image.tar,rewrite-timestamp=true
# from a context staged with `clearcutt-factory render --context-dir`.

ARG TARGETARCH

# ---- tool: kubectl (url 1.37.1, verified: checksum-file) ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:1c451d46a0d5c4e9f2b38e0e8d3e299564a1aa95c21973efcc1980a9d1d2e73e AS tool-kubectl-amd64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:65691ff77eb6fa44c908b77a1082c9f092c3b9733b5cefabec0d1104890e21a8 https://dl.k8s.io/release/v1.37.1/bin/linux/amd64/kubectl /src/kubectl
RUN install -D -m 0755 /src/kubectl /out/usr/local/bin/kubectl

FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:1c451d46a0d5c4e9f2b38e0e8d3e299564a1aa95c21973efcc1980a9d1d2e73e AS tool-kubectl-arm64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:ff749f4b78d9c4f1ec87307df9b50119ed819e2094aa9810cb9acffc3286c8c7 https://dl.k8s.io/release/v1.37.1/bin/linux/arm64/kubectl /src/kubectl
RUN install -D -m 0755 /src/kubectl /out/usr/local/bin/kubectl

FROM tool-kubectl-${TARGETARCH} AS tool-kubectl

# ---- image ----
# packages: dnf (amzn-2023)
FROM scratch AS pkgs-amd64
ADD --checksum=sha256:bb8447d1a37def80351dd016cf2f57889c14de1e0096467eeba921e9e1a84307 https://cdn.amazonlinux.com/al2023/blobstore/bb8447d1a37def80351dd016cf2f57889c14de1e0096467eeba921e9e1a84307/cracklib-2.9.6-27.amzn2023.0.2.x86_64.rpm /pkgs/cracklib-2.9.6-27.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:543e1b7ec49aa2077ebe1aab0926491dcff15909c8ecbad26dc6f489909a4645 https://cdn.amazonlinux.com/al2023/blobstore/543e1b7ec49aa2077ebe1aab0926491dcff15909c8ecbad26dc6f489909a4645/git-2.50.1-1.amzn2023.0.1.x86_64.rpm /pkgs/git-2.50.1-1.amzn2023.0.1.x86_64.rpm
ADD --checksum=sha256:1a266c41e66b0dca131ea2cb616588d75b580d2bfbb8b67a6504280ee90d640c https://cdn.amazonlinux.com/al2023/blobstore/1a266c41e66b0dca131ea2cb616588d75b580d2bfbb8b67a6504280ee90d640c/git-core-2.50.1-1.amzn2023.0.1.x86_64.rpm /pkgs/git-core-2.50.1-1.amzn2023.0.1.x86_64.rpm
ADD --checksum=sha256:fda1bad77b048f036af09aa9d39c55ff672d7eb8d594caa0ad3db3ae2d5badab https://cdn.amazonlinux.com/al2023/blobstore/fda1bad77b048f036af09aa9d39c55ff672d7eb8d594caa0ad3db3ae2d5badab/git-core-doc-2.50.1-1.amzn2023.0.1.noarch.rpm /pkgs/git-core-doc-2.50.1-1.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:b2e598a26b1d5c450a7f8939ea8e5244c59183f89dcf025193fdd2333b831862 https://cdn.amazonlinux.com/al2023/blobstore/b2e598a26b1d5c450a7f8939ea8e5244c59183f89dcf025193fdd2333b831862/groff-base-1.22.4-7.amzn2023.0.2.x86_64.rpm /pkgs/groff-base-1.22.4-7.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:9fa69b95d6404145efb642e88fd09b09f3c5addc74dcd87a7980d245abdc0d60 https://cdn.amazonlinux.com/al2023/blobstore/9fa69b95d6404145efb642e88fd09b09f3c5addc74dcd87a7980d245abdc0d60/gzip-1.12-1.amzn2023.0.1.x86_64.rpm /pkgs/gzip-1.12-1.amzn2023.0.1.x86_64.rpm
ADD --checksum=sha256:be649633b3d94a464761d36ec0e39f96fe90a71cac7a9783fb95467c0d171f1a https://cdn.amazonlinux.com/al2023/blobstore/be649633b3d94a464761d36ec0e39f96fe90a71cac7a9783fb95467c0d171f1a/jq-1.8.1-60.amzn2023.x86_64.rpm /pkgs/jq-1.8.1-60.amzn2023.x86_64.rpm
ADD --checksum=sha256:2020c283aab8789ae5ccb743966e0670366a6dd23f8c14b9b6ea0a4f518bd1c2 https://cdn.amazonlinux.com/al2023/blobstore/2020c283aab8789ae5ccb743966e0670366a6dd23f8c14b9b6ea0a4f518bd1c2/less-608-2.amzn2023.0.2.x86_64.rpm /pkgs/less-608-2.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:7806603ced381458bd3af5376193deab9fce5a4e0afe349425533388a41648e6 https://cdn.amazonlinux.com/al2023/blobstore/7806603ced381458bd3af5376193deab9fce5a4e0afe349425533388a41648e6/libcbor-0.7.0-3.amzn2023.0.2.x86_64.rpm /pkgs/libcbor-0.7.0-3.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:4a3cb4434afe2c672eb3dfd214d0004c0e3e262446317d19ec4a4adc18fd182d https://cdn.amazonlinux.com/al2023/blobstore/4a3cb4434afe2c672eb3dfd214d0004c0e3e262446317d19ec4a4adc18fd182d/libdb-5.3.28-49.amzn2023.0.2.x86_64.rpm /pkgs/libdb-5.3.28-49.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:a4cb17b3a374cb11dbb06565cace720d0223be76185676b9e41f5b21a4f7fdd3 https://cdn.amazonlinux.com/al2023/blobstore/a4cb17b3a374cb11dbb06565cace720d0223be76185676b9e41f5b21a4f7fdd3/libeconf-0.7.9-1.amzn2023.0.1.x86_64.rpm /pkgs/libeconf-0.7.9-1.amzn2023.0.1.x86_64.rpm
ADD --checksum=sha256:b6a143dcd3b961516066cba842b3bebb460ce0d7304d42f0aa6fbcb195cc2e77 https://cdn.amazonlinux.com/al2023/blobstore/b6a143dcd3b961516066cba842b3bebb460ce0d7304d42f0aa6fbcb195cc2e77/libedit-3.1-38.20210714cvs.amzn2023.0.2.x86_64.rpm /pkgs/libedit-3.1-38.20210714cvs.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:73c32611713978f5a8d63ae0abb3eae4a86ca6659e3a6c3fd131a7abb5647cc9 https://cdn.amazonlinux.com/al2023/blobstore/73c32611713978f5a8d63ae0abb3eae4a86ca6659e3a6c3fd131a7abb5647cc9/libfdisk-2.37.4-1.amzn2023.0.6.x86_64.rpm /pkgs/libfdisk-2.37.4-1.amzn2023.0.6.x86_64.rpm
ADD --checksum=sha256:1ff0e890e5703e8e96202ddfa669256371ee6ddeef078da1798c71bf51665089 https://cdn.amazonlinux.com/al2023/blobstore/1ff0e890e5703e8e96202ddfa669256371ee6ddeef078da1798c71bf51665089/libfido2-1.10.0-2.amzn2023.0.2.x86_64.rpm /pkgs/libfido2-1.10.0-2.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:b52306ac15341be5e2e4cc1ae20cd4c5c29017f29887b4eb88544823d1019c6e https://cdn.amazonlinux.com/al2023/blobstore/b52306ac15341be5e2e4cc1ae20cd4c5c29017f29887b4eb88544823d1019c6e/libpwquality-1.4.4-6.amzn2023.0.2.x86_64.rpm /pkgs/libpwquality-1.4.4-6.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:42921b0f73636651a559711e9a316618b0070d157fcc5f4f8bf9c6852e2a439b https://cdn.amazonlinux.com/al2023/blobstore/42921b0f73636651a559711e9a316618b0070d157fcc5f4f8bf9c6852e2a439b/libsemanage-3.4-5.amzn2023.0.2.x86_64.rpm /pkgs/libsemanage-3.4-5.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:afeccec96532b832b8c5f62052a11dc2e16e6774eb0c6fa2f243de329472c108 https://cdn.amazonlinux.com/al2023/blobstore/afeccec96532b832b8c5f62052a11dc2e16e6774eb0c6fa2f243de329472c108/libutempter-1.2.1-4.amzn2023.0.2.x86_64.rpm /pkgs/libutempter-1.2.1-4.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:7b576935e894f7ea79b5946b295702eda985a166443a39b3f622c51ec2ee29ba https://cdn.amazonlinux.com/al2023/blobstore/7b576935e894f7ea79b5946b295702eda985a166443a39b3f622c51ec2ee29ba/ncurses-6.6-1.amzn2023.0.1.x86_64.rpm /pkgs/ncurses-6.6-1.amzn2023.0.1.x86_64.rpm
ADD --checksum=sha256:37afc42e5e5c94f34d7b0f4efc1e7f5bd68b49b1eca42bb4cf9b69e53cbdadd7 https://cdn.amazonlinux.com/al2023/blobstore/37afc42e5e5c94f34d7b0f4efc1e7f5bd68b49b1eca42bb4cf9b69e53cbdadd7/oniguruma-6.9.7.1-1.amzn2023.0.2.x86_64.rpm /pkgs/oniguruma-6.9.7.1-1.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:499241bd6cea955073b8849897eb2a80132f921de638ed48a0053fa7f76c6c49 https://cdn.amazonlinux.com/al2023/blobstore/499241bd6cea955073b8849897eb2a80132f921de638ed48a0053fa7f76c6c49/openssh-9.9p1-10.amzn2023.0.2.x86_64.rpm /pkgs/openssh-9.9p1-10.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:1f455955d28b306e9ce0c20d9d412778a590efa588f2935a7f30c82651e6eca8 https://cdn.amazonlinux.com/al2023/blobstore/1f455955d28b306e9ce0c20d9d412778a590efa588f2935a7f30c82651e6eca8/openssh-clients-9.9p1-10.amzn2023.0.2.x86_64.rpm /pkgs/openssh-clients-9.9p1-10.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:3664efb5954a1c8c01c3600da2418cd5c8fa1f2323bc1200aa3a13edcee64540 https://cdn.amazonlinux.com/al2023/blobstore/3664efb5954a1c8c01c3600da2418cd5c8fa1f2323bc1200aa3a13edcee64540/pam-1.5.1-8.amzn2023.0.8.x86_64.rpm /pkgs/pam-1.5.1-8.amzn2023.0.8.x86_64.rpm
ADD --checksum=sha256:92e77a021179562062b341598a15ebce9c3675ae66190109f81fa3f70a62ef72 https://cdn.amazonlinux.com/al2023/blobstore/92e77a021179562062b341598a15ebce9c3675ae66190109f81fa3f70a62ef72/perl-AutoLoader-5.74-477.amzn2023.0.9.noarch.rpm /pkgs/perl-AutoLoader-5.74-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:b1bc19056016824d329e0dbc93487269cd6bb50d80cefcb47d8f0baac9f15c1b https://cdn.amazonlinux.com/al2023/blobstore/b1bc19056016824d329e0dbc93487269cd6bb50d80cefcb47d8f0baac9f15c1b/perl-B-1.80-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-B-1.80-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:42b2587510e52183fd864462776692da7c93959498c51882937c69c001d09543 https://cdn.amazonlinux.com/al2023/blobstore/42b2587510e52183fd864462776692da7c93959498c51882937c69c001d09543/perl-Carp-1.50-458.amzn2023.0.2.noarch.rpm /pkgs/perl-Carp-1.50-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:85acac1663490b4fa7d953aa5b5a4aa694247b7036a6bb2c94ba2abe72a110c1 https://cdn.amazonlinux.com/al2023/blobstore/85acac1663490b4fa7d953aa5b5a4aa694247b7036a6bb2c94ba2abe72a110c1/perl-Class-Struct-0.66-477.amzn2023.0.9.noarch.rpm /pkgs/perl-Class-Struct-0.66-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:2092d31eadbf312841e75c3bc01e162f58c80c85acb822bc4a15d5b51cf81400 https://cdn.amazonlinux.com/al2023/blobstore/2092d31eadbf312841e75c3bc01e162f58c80c85acb822bc4a15d5b51cf81400/perl-Data-Dumper-2.191-522.amzn2023.0.3.x86_64.rpm /pkgs/perl-Data-Dumper-2.191-522.amzn2023.0.3.x86_64.rpm
ADD --checksum=sha256:748b77b68271309f203b7c9a47c0504cfd869bd6e9a3e8c2978d646d9318ce6f https://cdn.amazonlinux.com/al2023/blobstore/748b77b68271309f203b7c9a47c0504cfd869bd6e9a3e8c2978d646d9318ce6f/perl-Digest-1.20-1.amzn2023.0.2.noarch.rpm /pkgs/perl-Digest-1.20-1.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:797bc7f38afa2a14695420d3b263a101f1d9f8e2a31f96945d15397ece1733ae https://cdn.amazonlinux.com/al2023/blobstore/797bc7f38afa2a14695420d3b263a101f1d9f8e2a31f96945d15397ece1733ae/perl-Digest-MD5-2.59-521.amzn2023.0.2.x86_64.rpm /pkgs/perl-Digest-MD5-2.59-521.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:20bc995835194010d9dcc161250c8d7e0dcb38cf2ba2fd7de65d005312d3fb88 https://cdn.amazonlinux.com/al2023/blobstore/20bc995835194010d9dcc161250c8d7e0dcb38cf2ba2fd7de65d005312d3fb88/perl-DynaLoader-1.47-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-DynaLoader-1.47-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:32593e5b5910d3535137468beb50bd201bf299d3392e11a643dc4c323ddb66dc https://cdn.amazonlinux.com/al2023/blobstore/32593e5b5910d3535137468beb50bd201bf299d3392e11a643dc4c323ddb66dc/perl-Encode-3.21-520.amzn2023.0.2.x86_64.rpm /pkgs/perl-Encode-3.21-520.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:4369d2a2819ed505ac9c735918467f53e10918aac7f3cde8421577ffc1ea54f0 https://cdn.amazonlinux.com/al2023/blobstore/4369d2a2819ed505ac9c735918467f53e10918aac7f3cde8421577ffc1ea54f0/perl-Errno-1.30-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-Errno-1.30-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:f36b82cf338b8f4fe64dab130e9a1f64c1fa2056505c50bedd0bbdf89b0c5fb7 https://cdn.amazonlinux.com/al2023/blobstore/f36b82cf338b8f4fe64dab130e9a1f64c1fa2056505c50bedd0bbdf89b0c5fb7/perl-Error-0.17030-2.amzn2023.0.1.noarch.rpm /pkgs/perl-Error-0.17030-2.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:d9a5d807e3c9482cdbda77d93514cab12a3c653e823b66762b442afffcb1275c https://cdn.amazonlinux.com/al2023/blobstore/d9a5d807e3c9482cdbda77d93514cab12a3c653e823b66762b442afffcb1275c/perl-Exporter-5.79-520.amzn2023.0.1.noarch.rpm /pkgs/perl-Exporter-5.79-520.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:909f8410030374a7152ee6bd97928a0ce268332e8862ac890eadc707541ca463 https://cdn.amazonlinux.com/al2023/blobstore/909f8410030374a7152ee6bd97928a0ce268332e8862ac890eadc707541ca463/perl-Fcntl-1.13-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-Fcntl-1.13-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:8ab174d84bc955b4ec725c72540be00def274ff0c5d88e16258889ad26b0b674 https://cdn.amazonlinux.com/al2023/blobstore/8ab174d84bc955b4ec725c72540be00def274ff0c5d88e16258889ad26b0b674/perl-File-Basename-2.85-477.amzn2023.0.9.noarch.rpm /pkgs/perl-File-Basename-2.85-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:94f22e6d3251dcaa03c8c60db1dfc4cdf6ae100311931fb3f1463bf2b09fb468 https://cdn.amazonlinux.com/al2023/blobstore/94f22e6d3251dcaa03c8c60db1dfc4cdf6ae100311931fb3f1463bf2b09fb468/perl-File-Find-1.37-477.amzn2023.0.9.noarch.rpm /pkgs/perl-File-Find-1.37-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:fdf5e0a89033df3dc742d3df4ac2d409dfbdcdc6a8f5e78cb1f245028eeae76e https://cdn.amazonlinux.com/al2023/blobstore/fdf5e0a89033df3dc742d3df4ac2d409dfbdcdc6a8f5e78cb1f245028eeae76e/perl-File-Path-2.18-2.amzn2023.0.2.noarch.rpm /pkgs/perl-File-Path-2.18-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:71bbff5e70cd3c4ee885125e645b6541527b68acef1621d8d2b7642cf9b8815d https://cdn.amazonlinux.com/al2023/blobstore/71bbff5e70cd3c4ee885125e645b6541527b68acef1621d8d2b7642cf9b8815d/perl-File-Temp-0.231.200-2.amzn2023.0.1.noarch.rpm /pkgs/perl-File-Temp-0.231.200-2.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:20a92ca73b571376767807197722b63bb1b15ade433cdda837e31feacc88a827 https://cdn.amazonlinux.com/al2023/blobstore/20a92ca73b571376767807197722b63bb1b15ade433cdda837e31feacc88a827/perl-File-stat-1.09-477.amzn2023.0.9.noarch.rpm /pkgs/perl-File-stat-1.09-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:0e9cff91bdc4994e5318db43742096a8a506b275531493a32bb0d3fb4ca5f9c7 https://cdn.amazonlinux.com/al2023/blobstore/0e9cff91bdc4994e5318db43742096a8a506b275531493a32bb0d3fb4ca5f9c7/perl-FileHandle-2.03-477.amzn2023.0.9.noarch.rpm /pkgs/perl-FileHandle-2.03-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:1fe9214496235881c15fbeb7ff35b4fc69a72aa6a684031da7895cf136f94526 https://cdn.amazonlinux.com/al2023/blobstore/1fe9214496235881c15fbeb7ff35b4fc69a72aa6a684031da7895cf136f94526/perl-Getopt-Long-2.58-521.amzn2023.0.1.noarch.rpm /pkgs/perl-Getopt-Long-2.58-521.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:a2d2d9dee73a8145db7716c7e6a5373ec64df8d369097f196ca0c1f9293d0e71 https://cdn.amazonlinux.com/al2023/blobstore/a2d2d9dee73a8145db7716c7e6a5373ec64df8d369097f196ca0c1f9293d0e71/perl-Getopt-Std-1.12-477.amzn2023.0.9.noarch.rpm /pkgs/perl-Getopt-Std-1.12-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:f4efe6e89ee5731988c75632afb34f33501fdb15ee18ebfac8573c229e15b6a2 https://cdn.amazonlinux.com/al2023/blobstore/f4efe6e89ee5731988c75632afb34f33501fdb15ee18ebfac8573c229e15b6a2/perl-Git-2.50.1-1.amzn2023.0.1.noarch.rpm /pkgs/perl-Git-2.50.1-1.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:c54ed018789f4542c8c42ce359c8ec93be15b213cbabe8641f8fdbc843eeab71 https://cdn.amazonlinux.com/al2023/blobstore/c54ed018789f4542c8c42ce359c8ec93be15b213cbabe8641f8fdbc843eeab71/perl-HTTP-Tiny-0.092-2.amzn2023.0.2.noarch.rpm /pkgs/perl-HTTP-Tiny-0.092-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:e1d0f31cc3bb9693164851e7599d9ba46c86cc18aee5bf9a99aa4e1d8d4cd6f0 https://cdn.amazonlinux.com/al2023/blobstore/e1d0f31cc3bb9693164851e7599d9ba46c86cc18aee5bf9a99aa4e1d8d4cd6f0/perl-IO-1.43-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-IO-1.43-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:20cdc381e34496f10affd266bd855603e0b34966273a1929edc60cccc2d05479 https://cdn.amazonlinux.com/al2023/blobstore/20cdc381e34496f10affd266bd855603e0b34966273a1929edc60cccc2d05479/perl-IO-Socket-IP-0.43-522.amzn2023.0.1.noarch.rpm /pkgs/perl-IO-Socket-IP-0.43-522.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:0de0213952bf748d58aa1935d515f3cf77ae5dade378783f77ccef245f934446 https://cdn.amazonlinux.com/al2023/blobstore/0de0213952bf748d58aa1935d515f3cf77ae5dade378783f77ccef245f934446/perl-IO-Socket-SSL-2.075-1.amzn2023.0.3.noarch.rpm /pkgs/perl-IO-Socket-SSL-2.075-1.amzn2023.0.3.noarch.rpm
ADD --checksum=sha256:285d0735f443570fd6a68ba41024d2239bc650e5a09ce9779caf0f6ffca05703 https://cdn.amazonlinux.com/al2023/blobstore/285d0735f443570fd6a68ba41024d2239bc650e5a09ce9779caf0f6ffca05703/perl-IPC-Open3-1.21-477.amzn2023.0.9.noarch.rpm /pkgs/perl-IPC-Open3-1.21-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:54b5bc2298fecbe63dc5c49199998030408fc00db4b898b71db3ad11b46941bc https://cdn.amazonlinux.com/al2023/blobstore/54b5bc2298fecbe63dc5c49199998030408fc00db4b898b71db3ad11b46941bc/perl-MIME-Base64-3.16-2.amzn2023.0.3.x86_64.rpm /pkgs/perl-MIME-Base64-3.16-2.amzn2023.0.3.x86_64.rpm
ADD --checksum=sha256:875fa4b4da326b5c8ff2aee7a825883ff4b4841f81d0fb119aed3df3265198c6 https://cdn.amazonlinux.com/al2023/blobstore/875fa4b4da326b5c8ff2aee7a825883ff4b4841f81d0fb119aed3df3265198c6/perl-Net-SSLeay-1.94-3.amzn2023.0.5.x86_64.rpm /pkgs/perl-Net-SSLeay-1.94-3.amzn2023.0.5.x86_64.rpm
ADD --checksum=sha256:200caf401cb8e42c0c6b8d0def3c7870e0dabd623c10e3406d169f1c6790b619 https://cdn.amazonlinux.com/al2023/blobstore/200caf401cb8e42c0c6b8d0def3c7870e0dabd623c10e3406d169f1c6790b619/perl-POSIX-1.94-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-POSIX-1.94-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:44a9f1d689aa96ca2337a7720964fb9733fa632fcbe9b802de9d1876068eea55 https://cdn.amazonlinux.com/al2023/blobstore/44a9f1d689aa96ca2337a7720964fb9733fa632fcbe9b802de9d1876068eea55/perl-PathTools-3.78-459.amzn2023.0.3.x86_64.rpm /pkgs/perl-PathTools-3.78-459.amzn2023.0.3.x86_64.rpm
ADD --checksum=sha256:a386219cff753cd97d213c92fe12262dd000dd08e76c4604739139789b28101a https://cdn.amazonlinux.com/al2023/blobstore/a386219cff753cd97d213c92fe12262dd000dd08e76c4604739139789b28101a/perl-Pod-Escapes-1.07-458.amzn2023.0.2.noarch.rpm /pkgs/perl-Pod-Escapes-1.07-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:b3fdf3be498c4ce41189b18365e82378e69ce12b7813fed78a391021aa10f4dd https://cdn.amazonlinux.com/al2023/blobstore/b3fdf3be498c4ce41189b18365e82378e69ce12b7813fed78a391021aa10f4dd/perl-Pod-Perldoc-3.28.01-459.amzn2023.0.3.noarch.rpm /pkgs/perl-Pod-Perldoc-3.28.01-459.amzn2023.0.3.noarch.rpm
ADD --checksum=sha256:999e5ff428f5417f43b965dcb197a2f5d9dbefbfbfc0d108bbccccc2603624dd https://cdn.amazonlinux.com/al2023/blobstore/999e5ff428f5417f43b965dcb197a2f5d9dbefbfbfc0d108bbccccc2603624dd/perl-Pod-Simple-3.42-2.amzn2023.0.2.noarch.rpm /pkgs/perl-Pod-Simple-3.42-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:155757772d960a031bd9cfb1c80b4467cc9a91f91e3696613509e19f4949ede1 https://cdn.amazonlinux.com/al2023/blobstore/155757772d960a031bd9cfb1c80b4467cc9a91f91e3696613509e19f4949ede1/perl-Pod-Usage-2.01-2.amzn2023.0.2.noarch.rpm /pkgs/perl-Pod-Usage-2.01-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:4e4ba0bc3e90e46dbf99003f21d3aaf1580b1e1806f7c5d49ee5befb52f487bb https://cdn.amazonlinux.com/al2023/blobstore/4e4ba0bc3e90e46dbf99003f21d3aaf1580b1e1806f7c5d49ee5befb52f487bb/perl-Scalar-List-Utils-1.56-459.amzn2023.0.3.x86_64.rpm /pkgs/perl-Scalar-List-Utils-1.56-459.amzn2023.0.3.x86_64.rpm
ADD --checksum=sha256:feb38157475d06c6503174483af12a01d808292ff6b475a657faff1116ae9373 https://cdn.amazonlinux.com/al2023/blobstore/feb38157475d06c6503174483af12a01d808292ff6b475a657faff1116ae9373/perl-SelectSaver-1.02-477.amzn2023.0.9.noarch.rpm /pkgs/perl-SelectSaver-1.02-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:2e31c1d6ffa9048e3223c520bcc3dc1cd18347944ce2746f1933264bf80295dd https://cdn.amazonlinux.com/al2023/blobstore/2e31c1d6ffa9048e3223c520bcc3dc1cd18347944ce2746f1933264bf80295dd/perl-Socket-2.032-1.amzn2023.0.4.x86_64.rpm /pkgs/perl-Socket-2.032-1.amzn2023.0.4.x86_64.rpm
ADD --checksum=sha256:1defb65ab19ff60724deacea7976124f3a0cf8482400ab0815a88b2dd87d7716 https://cdn.amazonlinux.com/al2023/blobstore/1defb65ab19ff60724deacea7976124f3a0cf8482400ab0815a88b2dd87d7716/perl-Storable-3.37-522.amzn2023.0.2.x86_64.rpm /pkgs/perl-Storable-3.37-522.amzn2023.0.2.x86_64.rpm
ADD --checksum=sha256:9ce31d21a9382ae83d826dd28e08e1f28235700c9253f885912a058385054ff7 https://cdn.amazonlinux.com/al2023/blobstore/9ce31d21a9382ae83d826dd28e08e1f28235700c9253f885912a058385054ff7/perl-Symbol-1.08-477.amzn2023.0.9.noarch.rpm /pkgs/perl-Symbol-1.08-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:438a1331f6f9ef4ee91d61cdc81181815f1e4d1b62fe021cb71cd670f8fbe24e https://cdn.amazonlinux.com/al2023/blobstore/438a1331f6f9ef4ee91d61cdc81181815f1e4d1b62fe021cb71cd670f8fbe24e/perl-Term-ANSIColor-5.01-459.amzn2023.0.2.noarch.rpm /pkgs/perl-Term-ANSIColor-5.01-459.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:0311f36e7c4d68dde8f04831e24f6da51f2e889ce9840a7df1aa9118a1c63bea https://cdn.amazonlinux.com/al2023/blobstore/0311f36e7c4d68dde8f04831e24f6da51f2e889ce9840a7df1aa9118a1c63bea/perl-Term-Cap-1.17-458.amzn2023.0.2.noarch.rpm /pkgs/perl-Term-Cap-1.17-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:26dc79db7531c3cfac0dbf03ba5fcd7554ed22a003952b87e0032286960dc6fe https://cdn.amazonlinux.com/al2023/blobstore/26dc79db7531c3cfac0dbf03ba5fcd7554ed22a003952b87e0032286960dc6fe/perl-TermReadKey-2.38-9.amzn2023.0.3.x86_64.rpm /pkgs/perl-TermReadKey-2.38-9.amzn2023.0.3.x86_64.rpm
ADD --checksum=sha256:36a23239257b8caf0ab3d6b869609bf6e5f2b0b35fe233cc995ec2b6bfeb824d https://cdn.amazonlinux.com/al2023/blobstore/36a23239257b8caf0ab3d6b869609bf6e5f2b0b35fe233cc995ec2b6bfeb824d/perl-Text-ParseWords-3.30-458.amzn2023.0.2.noarch.rpm /pkgs/perl-Text-ParseWords-3.30-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:c26b33388c5e1addd19255110a48797eefd23476a911f72338d422c212d0c2d8 https://cdn.amazonlinux.com/al2023/blobstore/c26b33388c5e1addd19255110a48797eefd23476a911f72338d422c212d0c2d8/perl-Text-Tabs%2BWrap-2021.0726-1.amzn2023.0.1.noarch.rpm /pkgs/perl-Text-Tabs+Wrap-2021.0726-1.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:d00332723a9e8edc7b95a788da64f65aaf23dd20781fa1559355b11c95b88196 https://cdn.amazonlinux.com/al2023/blobstore/d00332723a9e8edc7b95a788da64f65aaf23dd20781fa1559355b11c95b88196/perl-Time-HiRes-1.9764-460.amzn2023.0.3.x86_64.rpm /pkgs/perl-Time-HiRes-1.9764-460.amzn2023.0.3.x86_64.rpm
ADD --checksum=sha256:ee39bb8d079e17afe6cfb4114add60c7cee040baf2e4d8aac7bf6c2f8bf5c64a https://cdn.amazonlinux.com/al2023/blobstore/ee39bb8d079e17afe6cfb4114add60c7cee040baf2e4d8aac7bf6c2f8bf5c64a/perl-Time-Local-1.300-5.amzn2023.0.2.noarch.rpm /pkgs/perl-Time-Local-1.300-5.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:71d324651ea6a43c6db2e98cd7f8a6555e8e458d02782ae299c31ccc5c13fb7f https://cdn.amazonlinux.com/al2023/blobstore/71d324651ea6a43c6db2e98cd7f8a6555e8e458d02782ae299c31ccc5c13fb7f/perl-URI-5.18-1.amzn2023.0.1.noarch.rpm /pkgs/perl-URI-5.18-1.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:715523a90d6bc31a41139412c57dcba8eccfdcc59a1cbc2276228b5b744127b5 https://cdn.amazonlinux.com/al2023/blobstore/715523a90d6bc31a41139412c57dcba8eccfdcc59a1cbc2276228b5b744127b5/perl-base-2.27-477.amzn2023.0.9.noarch.rpm /pkgs/perl-base-2.27-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:b70603ae417a1949a43aa95bd60219d30a81bdb80ef2a379c2fd473c4c19920f https://cdn.amazonlinux.com/al2023/blobstore/b70603ae417a1949a43aa95bd60219d30a81bdb80ef2a379c2fd473c4c19920f/perl-constant-1.33-459.amzn2023.0.2.noarch.rpm /pkgs/perl-constant-1.33-459.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:e9458f5ded25d45e3937165062de73243cccd0fa864eb91fcedd3007aefceb8e https://cdn.amazonlinux.com/al2023/blobstore/e9458f5ded25d45e3937165062de73243cccd0fa864eb91fcedd3007aefceb8e/perl-if-0.60.800-477.amzn2023.0.9.noarch.rpm /pkgs/perl-if-0.60.800-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:c1f17948d8607cb936f340767b4badea3316e4b4984b4caf705880f526688ac5 https://cdn.amazonlinux.com/al2023/blobstore/c1f17948d8607cb936f340767b4badea3316e4b4984b4caf705880f526688ac5/perl-interpreter-5.32.1-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-interpreter-5.32.1-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:27da2c47456c0c13650c515f3ec09050e9ca4621fc3305ea1facdff809f1e70d https://cdn.amazonlinux.com/al2023/blobstore/27da2c47456c0c13650c515f3ec09050e9ca4621fc3305ea1facdff809f1e70d/perl-lib-0.65-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-lib-0.65-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:9b9ac714d48d9fb3debff9bb4147747cdaf000617cc6f6e59a30ac6ce10e98c6 https://cdn.amazonlinux.com/al2023/blobstore/9b9ac714d48d9fb3debff9bb4147747cdaf000617cc6f6e59a30ac6ce10e98c6/perl-libnet-3.13-2.amzn2023.0.2.noarch.rpm /pkgs/perl-libnet-3.13-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:4562304725e8b461859dd7094bc3414a03399f53b3ed6e3a3e11b20986fa1334 https://cdn.amazonlinux.com/al2023/blobstore/4562304725e8b461859dd7094bc3414a03399f53b3ed6e3a3e11b20986fa1334/perl-libs-5.32.1-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-libs-5.32.1-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:5137f9c1839e99e40dcd2ba0f1fd2486adb925d3bc1d5e565abb4c10e3b6cc9e https://cdn.amazonlinux.com/al2023/blobstore/5137f9c1839e99e40dcd2ba0f1fd2486adb925d3bc1d5e565abb4c10e3b6cc9e/perl-mro-1.23-477.amzn2023.0.9.x86_64.rpm /pkgs/perl-mro-1.23-477.amzn2023.0.9.x86_64.rpm
ADD --checksum=sha256:b60facd58b0579eaba5eb8ba6a9d66549f1b25c7eb49fe666fe8c8e52388d7ed https://cdn.amazonlinux.com/al2023/blobstore/b60facd58b0579eaba5eb8ba6a9d66549f1b25c7eb49fe666fe8c8e52388d7ed/perl-overload-1.31-477.amzn2023.0.9.noarch.rpm /pkgs/perl-overload-1.31-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:447c81b47a67c4033165463c6954d02ea5217a6469a27888a219bac63238f783 https://cdn.amazonlinux.com/al2023/blobstore/447c81b47a67c4033165463c6954d02ea5217a6469a27888a219bac63238f783/perl-overloading-0.02-477.amzn2023.0.9.noarch.rpm /pkgs/perl-overloading-0.02-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:af978755a2aec4cb77ba4c7eedd05ce8de99678d8a07552b72435acb2cea89ca https://cdn.amazonlinux.com/al2023/blobstore/af978755a2aec4cb77ba4c7eedd05ce8de99678d8a07552b72435acb2cea89ca/perl-parent-0.238-458.amzn2023.0.2.noarch.rpm /pkgs/perl-parent-0.238-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:24bdbf834529c67dbcfa23901bb315a2e610ba79075590b1e95e949d37a8918c https://cdn.amazonlinux.com/al2023/blobstore/24bdbf834529c67dbcfa23901bb315a2e610ba79075590b1e95e949d37a8918c/perl-podlators-4.14-458.amzn2023.0.2.noarch.rpm /pkgs/perl-podlators-4.14-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:311607ac8ad7d4d1635129bf43595dbb26a31620bf5839dc148e60bf82eb4b69 https://cdn.amazonlinux.com/al2023/blobstore/311607ac8ad7d4d1635129bf43595dbb26a31620bf5839dc148e60bf82eb4b69/perl-subs-1.03-477.amzn2023.0.9.noarch.rpm /pkgs/perl-subs-1.03-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:07b1c37e6e8b836a99fd36e53cf01ad686f325296fae4455efc8742969552867 https://cdn.amazonlinux.com/al2023/blobstore/07b1c37e6e8b836a99fd36e53cf01ad686f325296fae4455efc8742969552867/perl-vars-1.05-477.amzn2023.0.9.noarch.rpm /pkgs/perl-vars-1.05-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:bf29c6750bc92a3ca2eb0857ae91c3d28b935f744ee808d1b4517f74f8397ae1 https://cdn.amazonlinux.com/al2023/blobstore/bf29c6750bc92a3ca2eb0857ae91c3d28b935f744ee808d1b4517f74f8397ae1/shadow-utils-4.9-12.amzn2023.0.4.x86_64.rpm /pkgs/shadow-utils-4.9-12.amzn2023.0.4.x86_64.rpm
ADD --checksum=sha256:39a529d8961f85e2b6a78a45647c59e78652a7487b75a8a250431dddce57b562 https://cdn.amazonlinux.com/al2023/blobstore/39a529d8961f85e2b6a78a45647c59e78652a7487b75a8a250431dddce57b562/systemd-libs-252.23-14.amzn2023.x86_64.rpm /pkgs/systemd-libs-252.23-14.amzn2023.x86_64.rpm
ADD --checksum=sha256:06d66285ecaec0f943b4dc24290c6dfefd291f1d2d6e0a3fb26b966ee7c27f55 https://cdn.amazonlinux.com/al2023/blobstore/06d66285ecaec0f943b4dc24290c6dfefd291f1d2d6e0a3fb26b966ee7c27f55/tar-1.34-1.amzn2023.0.4.x86_64.rpm /pkgs/tar-1.34-1.amzn2023.0.4.x86_64.rpm
ADD --checksum=sha256:6b7b568461a81bd209d3e95f44d8cf49df9798296141bffca8d21c2fec477212 https://cdn.amazonlinux.com/al2023/blobstore/6b7b568461a81bd209d3e95f44d8cf49df9798296141bffca8d21c2fec477212/util-linux-2.37.4-1.amzn2023.0.6.x86_64.rpm /pkgs/util-linux-2.37.4-1.amzn2023.0.6.x86_64.rpm
ADD --checksum=sha256:b9e31f14cc83fcbc159267e237c3e6ba4489329d064f938a19530c64f006060c https://cdn.amazonlinux.com/al2023/blobstore/b9e31f14cc83fcbc159267e237c3e6ba4489329d064f938a19530c64f006060c/util-linux-core-2.37.4-1.amzn2023.0.6.x86_64.rpm /pkgs/util-linux-core-2.37.4-1.amzn2023.0.6.x86_64.rpm

FROM amazonlinux:2023@sha256:8ed3c0a996841537f75607e7d1de2114d8150391f75792e8da9268738547e73f AS packages-amd64
ARG SOURCE_DATE_EPOCH
RUN --mount=type=bind,from=pkgs-amd64,source=/pkgs,target=/tmp/factory-pkgs <<'FACTORY_EOF'
set -eu
rpm -Uvh --quiet /tmp/factory-pkgs/*.rpm
rm -rf /var/cache/ldconfig/aux-cache
first=$(ls /tmp/factory-pkgs/*.rpm | head -n 1)
tid=$(rpm -q --qf '%{INSTALLTID}\n' "$(rpm -qp --nosignature --qf '%{NAME}' "$first")" | head -n 1)
for d in /usr/lib/sysimage/rpm /var/lib/rpm; do
  db="$d/rpmdb.sqlite"
  [ -f "$db" ] && [ ! -L "$d" ] || continue
  if [ -n "${SOURCE_DATE_EPOCH:-}" ] && [ "$tid" != "$SOURCE_DATE_EPOCH" ]; then
    python3 - "$db" "$tid" "$SOURCE_DATE_EPOCH" <<'PY'
import sqlite3, struct, sys
db, old, new = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
INSTALLTIME, INSTALLTID, INT32 = 1008, 1128, 4
c = sqlite3.connect(db)
for hnum, blob in c.execute("SELECT hnum, blob FROM Packages").fetchall():
    b = bytearray(blob)
    il = struct.unpack(">I", b[:4])[0]
    data, pos = 8 + il * 16, {}
    for i in range(il):
        tag, typ, off, cnt = struct.unpack(">IIII", b[8 + i * 16:24 + i * 16])
        if tag in (INSTALLTIME, INSTALLTID) and typ == INT32 and cnt == 1:
            pos[tag] = data + off
    if INSTALLTID in pos and struct.unpack(">I", b[pos[INSTALLTID]:pos[INSTALLTID] + 4])[0] == old:
        for p in pos.values():
            b[p:p + 4] = struct.pack(">I", new)
        c.execute("UPDATE Packages SET blob = ? WHERE hnum = ?", (bytes(b), hnum))
c.execute("UPDATE Installtid SET key = ? WHERE key = ?", (struct.pack("<I", new), struct.pack("<I", old)))
c.commit()
c.execute("PRAGMA wal_checkpoint(TRUNCATE)")
c.close()
PY
  fi
  if [ ! -s "$db-wal" ]; then rm -f "$db-wal" "$db-shm"; fi
done
FACTORY_EOF

FROM scratch AS pkgs-arm64
ADD --checksum=sha256:b738487623f55a447573777a8ce095149bd77cd27dbf018333a1211f7eaa0303 https://cdn.amazonlinux.com/al2023/blobstore/b738487623f55a447573777a8ce095149bd77cd27dbf018333a1211f7eaa0303/cracklib-2.9.6-27.amzn2023.0.2.aarch64.rpm /pkgs/cracklib-2.9.6-27.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:55b67a0a11dad39d1352e90ae13a79677170928d83a43fccaee3bc20b292d9bd https://cdn.amazonlinux.com/al2023/blobstore/55b67a0a11dad39d1352e90ae13a79677170928d83a43fccaee3bc20b292d9bd/git-2.50.1-1.amzn2023.0.1.aarch64.rpm /pkgs/git-2.50.1-1.amzn2023.0.1.aarch64.rpm
ADD --checksum=sha256:d16bc08a4def8729a665a1a46389482e6dba1c440abc3f45fd86e8851a437082 https://cdn.amazonlinux.com/al2023/blobstore/d16bc08a4def8729a665a1a46389482e6dba1c440abc3f45fd86e8851a437082/git-core-2.50.1-1.amzn2023.0.1.aarch64.rpm /pkgs/git-core-2.50.1-1.amzn2023.0.1.aarch64.rpm
ADD --checksum=sha256:fda1bad77b048f036af09aa9d39c55ff672d7eb8d594caa0ad3db3ae2d5badab https://cdn.amazonlinux.com/al2023/blobstore/fda1bad77b048f036af09aa9d39c55ff672d7eb8d594caa0ad3db3ae2d5badab/git-core-doc-2.50.1-1.amzn2023.0.1.noarch.rpm /pkgs/git-core-doc-2.50.1-1.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:d77b6c2a2488334158dfb9f8fe07adb1acb6a911f45e7042e2e09d3359d3b626 https://cdn.amazonlinux.com/al2023/blobstore/d77b6c2a2488334158dfb9f8fe07adb1acb6a911f45e7042e2e09d3359d3b626/groff-base-1.22.4-7.amzn2023.0.2.aarch64.rpm /pkgs/groff-base-1.22.4-7.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:a21bbe894f3ae1575c8b031ff0bf0708c8b329ddbd2882bc3688a6498f88c681 https://cdn.amazonlinux.com/al2023/blobstore/a21bbe894f3ae1575c8b031ff0bf0708c8b329ddbd2882bc3688a6498f88c681/gzip-1.12-1.amzn2023.0.1.aarch64.rpm /pkgs/gzip-1.12-1.amzn2023.0.1.aarch64.rpm
ADD --checksum=sha256:be1fee93bc2922ce5fa7275e6bc34f3e42bacf0c35ae61e32adbeb29470765b6 https://cdn.amazonlinux.com/al2023/blobstore/be1fee93bc2922ce5fa7275e6bc34f3e42bacf0c35ae61e32adbeb29470765b6/jq-1.8.1-60.amzn2023.aarch64.rpm /pkgs/jq-1.8.1-60.amzn2023.aarch64.rpm
ADD --checksum=sha256:6ae44cf6e07d4d58385ff03f7fd790a5ab1bc842d32d02acb7e33be15a0535ee https://cdn.amazonlinux.com/al2023/blobstore/6ae44cf6e07d4d58385ff03f7fd790a5ab1bc842d32d02acb7e33be15a0535ee/less-608-2.amzn2023.0.2.aarch64.rpm /pkgs/less-608-2.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:3483e1583e48693272bf6ed5d36996f93f6aff49e1b58c7eb0c688c54078f326 https://cdn.amazonlinux.com/al2023/blobstore/3483e1583e48693272bf6ed5d36996f93f6aff49e1b58c7eb0c688c54078f326/libcbor-0.7.0-3.amzn2023.0.2.aarch64.rpm /pkgs/libcbor-0.7.0-3.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:66577a3e1c7e35cab319a43b0d706fd77b28c351d53e843f9977f19685886238 https://cdn.amazonlinux.com/al2023/blobstore/66577a3e1c7e35cab319a43b0d706fd77b28c351d53e843f9977f19685886238/libdb-5.3.28-49.amzn2023.0.2.aarch64.rpm /pkgs/libdb-5.3.28-49.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:59e410c4d55614aba1227bb501323dc001f64178d74593bb2e820b0d06e16e22 https://cdn.amazonlinux.com/al2023/blobstore/59e410c4d55614aba1227bb501323dc001f64178d74593bb2e820b0d06e16e22/libeconf-0.7.9-1.amzn2023.0.1.aarch64.rpm /pkgs/libeconf-0.7.9-1.amzn2023.0.1.aarch64.rpm
ADD --checksum=sha256:e6d5f98ef0da46badfa9004ae5cfed50ac7d04fb9450618e2aadc7100a78e5ba https://cdn.amazonlinux.com/al2023/blobstore/e6d5f98ef0da46badfa9004ae5cfed50ac7d04fb9450618e2aadc7100a78e5ba/libedit-3.1-38.20210714cvs.amzn2023.0.2.aarch64.rpm /pkgs/libedit-3.1-38.20210714cvs.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:1c598d2d0efbdf2a511165fb40158c00bc128f4e7dfb22c025fc4e2cf255fcbe https://cdn.amazonlinux.com/al2023/blobstore/1c598d2d0efbdf2a511165fb40158c00bc128f4e7dfb22c025fc4e2cf255fcbe/libfdisk-2.37.4-1.amzn2023.0.6.aarch64.rpm /pkgs/libfdisk-2.37.4-1.amzn2023.0.6.aarch64.rpm
ADD --checksum=sha256:7789077f5745c791db57eb09e3f39a89c93ec0bb0a531040b0f4a9aa88b4f577 https://cdn.amazonlinux.com/al2023/blobstore/7789077f5745c791db57eb09e3f39a89c93ec0bb0a531040b0f4a9aa88b4f577/libfido2-1.10.0-2.amzn2023.0.2.aarch64.rpm /pkgs/libfido2-1.10.0-2.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:ba0e8c883f4b5b0d1207a08ad38aa64908508dc62fcb229bdb83eaa971638fc5 https://cdn.amazonlinux.com/al2023/blobstore/ba0e8c883f4b5b0d1207a08ad38aa64908508dc62fcb229bdb83eaa971638fc5/libpwquality-1.4.4-6.amzn2023.0.2.aarch64.rpm /pkgs/libpwquality-1.4.4-6.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:c7d58bb0b19724a6e697b8b33479c02e68f89c3814c821a775bd7eca7f5fb281 https://cdn.amazonlinux.com/al2023/blobstore/c7d58bb0b19724a6e697b8b33479c02e68f89c3814c821a775bd7eca7f5fb281/libsemanage-3.4-5.amzn2023.0.2.aarch64.rpm /pkgs/libsemanage-3.4-5.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:2720e8a260a3c0b5a5e41aff0419e8bce6abce36848b2867421f059162db3739 https://cdn.amazonlinux.com/al2023/blobstore/2720e8a260a3c0b5a5e41aff0419e8bce6abce36848b2867421f059162db3739/libutempter-1.2.1-4.amzn2023.0.2.aarch64.rpm /pkgs/libutempter-1.2.1-4.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:10858479901d3a934dbc15c3215a5ea2efe1ea4871b290083682a4c82562dd32 https://cdn.amazonlinux.com/al2023/blobstore/10858479901d3a934dbc15c3215a5ea2efe1ea4871b290083682a4c82562dd32/ncurses-6.6-1.amzn2023.0.1.aarch64.rpm /pkgs/ncurses-6.6-1.amzn2023.0.1.aarch64.rpm
ADD --checksum=sha256:92f6518bda8ba560503c1f7c53e2a35d96301e7ae4beb97b5b954560a09f5761 https://cdn.amazonlinux.com/al2023/blobstore/92f6518bda8ba560503c1f7c53e2a35d96301e7ae4beb97b5b954560a09f5761/oniguruma-6.9.7.1-1.amzn2023.0.2.aarch64.rpm /pkgs/oniguruma-6.9.7.1-1.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:7d10cf7fff40c3f177544941db842dab443f524d5cb821e11f9136c9e9f60afc https://cdn.amazonlinux.com/al2023/blobstore/7d10cf7fff40c3f177544941db842dab443f524d5cb821e11f9136c9e9f60afc/openssh-9.9p1-10.amzn2023.0.2.aarch64.rpm /pkgs/openssh-9.9p1-10.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:c618fc26048a8ed1c0b851b576b60205167260816b35c009fb041311452f31e0 https://cdn.amazonlinux.com/al2023/blobstore/c618fc26048a8ed1c0b851b576b60205167260816b35c009fb041311452f31e0/openssh-clients-9.9p1-10.amzn2023.0.2.aarch64.rpm /pkgs/openssh-clients-9.9p1-10.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:5beeffdd84bbb42da19409ffa3555371db63cc5efe1464f380f9756868dcfbbd https://cdn.amazonlinux.com/al2023/blobstore/5beeffdd84bbb42da19409ffa3555371db63cc5efe1464f380f9756868dcfbbd/pam-1.5.1-8.amzn2023.0.8.aarch64.rpm /pkgs/pam-1.5.1-8.amzn2023.0.8.aarch64.rpm
ADD --checksum=sha256:92e77a021179562062b341598a15ebce9c3675ae66190109f81fa3f70a62ef72 https://cdn.amazonlinux.com/al2023/blobstore/92e77a021179562062b341598a15ebce9c3675ae66190109f81fa3f70a62ef72/perl-AutoLoader-5.74-477.amzn2023.0.9.noarch.rpm /pkgs/perl-AutoLoader-5.74-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:a7de4cd2628f430f8af4035d13b198782127dde32bbdd0ea22e8b55785c11a78 https://cdn.amazonlinux.com/al2023/blobstore/a7de4cd2628f430f8af4035d13b198782127dde32bbdd0ea22e8b55785c11a78/perl-B-1.80-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-B-1.80-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:42b2587510e52183fd864462776692da7c93959498c51882937c69c001d09543 https://cdn.amazonlinux.com/al2023/blobstore/42b2587510e52183fd864462776692da7c93959498c51882937c69c001d09543/perl-Carp-1.50-458.amzn2023.0.2.noarch.rpm /pkgs/perl-Carp-1.50-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:85acac1663490b4fa7d953aa5b5a4aa694247b7036a6bb2c94ba2abe72a110c1 https://cdn.amazonlinux.com/al2023/blobstore/85acac1663490b4fa7d953aa5b5a4aa694247b7036a6bb2c94ba2abe72a110c1/perl-Class-Struct-0.66-477.amzn2023.0.9.noarch.rpm /pkgs/perl-Class-Struct-0.66-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:b892781d0a17b357088a111008fa80a7f74702aaa3bd14036449e380e242ddee https://cdn.amazonlinux.com/al2023/blobstore/b892781d0a17b357088a111008fa80a7f74702aaa3bd14036449e380e242ddee/perl-Data-Dumper-2.191-522.amzn2023.0.3.aarch64.rpm /pkgs/perl-Data-Dumper-2.191-522.amzn2023.0.3.aarch64.rpm
ADD --checksum=sha256:748b77b68271309f203b7c9a47c0504cfd869bd6e9a3e8c2978d646d9318ce6f https://cdn.amazonlinux.com/al2023/blobstore/748b77b68271309f203b7c9a47c0504cfd869bd6e9a3e8c2978d646d9318ce6f/perl-Digest-1.20-1.amzn2023.0.2.noarch.rpm /pkgs/perl-Digest-1.20-1.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:7bcbf37affb79029f8621d72a7a8cf020553009c3ad9158811a9069826261b0b https://cdn.amazonlinux.com/al2023/blobstore/7bcbf37affb79029f8621d72a7a8cf020553009c3ad9158811a9069826261b0b/perl-Digest-MD5-2.59-521.amzn2023.0.2.aarch64.rpm /pkgs/perl-Digest-MD5-2.59-521.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:e521b3621e658e7bfd96255893f7c9145ac97a747394c9203222a510405c7787 https://cdn.amazonlinux.com/al2023/blobstore/e521b3621e658e7bfd96255893f7c9145ac97a747394c9203222a510405c7787/perl-DynaLoader-1.47-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-DynaLoader-1.47-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:bbf8c6b73910bc9955e92ddbfa0228e652ac07d86a6e61692c73cdd0cae15cc1 https://cdn.amazonlinux.com/al2023/blobstore/bbf8c6b73910bc9955e92ddbfa0228e652ac07d86a6e61692c73cdd0cae15cc1/perl-Encode-3.21-520.amzn2023.0.2.aarch64.rpm /pkgs/perl-Encode-3.21-520.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:1201c4850c79fbd142216ade07ad6e3670c476f49477354d8d8a9b05b9812013 https://cdn.amazonlinux.com/al2023/blobstore/1201c4850c79fbd142216ade07ad6e3670c476f49477354d8d8a9b05b9812013/perl-Errno-1.30-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-Errno-1.30-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:f36b82cf338b8f4fe64dab130e9a1f64c1fa2056505c50bedd0bbdf89b0c5fb7 https://cdn.amazonlinux.com/al2023/blobstore/f36b82cf338b8f4fe64dab130e9a1f64c1fa2056505c50bedd0bbdf89b0c5fb7/perl-Error-0.17030-2.amzn2023.0.1.noarch.rpm /pkgs/perl-Error-0.17030-2.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:d9a5d807e3c9482cdbda77d93514cab12a3c653e823b66762b442afffcb1275c https://cdn.amazonlinux.com/al2023/blobstore/d9a5d807e3c9482cdbda77d93514cab12a3c653e823b66762b442afffcb1275c/perl-Exporter-5.79-520.amzn2023.0.1.noarch.rpm /pkgs/perl-Exporter-5.79-520.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:6b6ae610523e2bea4f65efc6c4976b874db4b30c670f9c6f3e4fa44abd3e0057 https://cdn.amazonlinux.com/al2023/blobstore/6b6ae610523e2bea4f65efc6c4976b874db4b30c670f9c6f3e4fa44abd3e0057/perl-Fcntl-1.13-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-Fcntl-1.13-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:8ab174d84bc955b4ec725c72540be00def274ff0c5d88e16258889ad26b0b674 https://cdn.amazonlinux.com/al2023/blobstore/8ab174d84bc955b4ec725c72540be00def274ff0c5d88e16258889ad26b0b674/perl-File-Basename-2.85-477.amzn2023.0.9.noarch.rpm /pkgs/perl-File-Basename-2.85-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:94f22e6d3251dcaa03c8c60db1dfc4cdf6ae100311931fb3f1463bf2b09fb468 https://cdn.amazonlinux.com/al2023/blobstore/94f22e6d3251dcaa03c8c60db1dfc4cdf6ae100311931fb3f1463bf2b09fb468/perl-File-Find-1.37-477.amzn2023.0.9.noarch.rpm /pkgs/perl-File-Find-1.37-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:fdf5e0a89033df3dc742d3df4ac2d409dfbdcdc6a8f5e78cb1f245028eeae76e https://cdn.amazonlinux.com/al2023/blobstore/fdf5e0a89033df3dc742d3df4ac2d409dfbdcdc6a8f5e78cb1f245028eeae76e/perl-File-Path-2.18-2.amzn2023.0.2.noarch.rpm /pkgs/perl-File-Path-2.18-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:71bbff5e70cd3c4ee885125e645b6541527b68acef1621d8d2b7642cf9b8815d https://cdn.amazonlinux.com/al2023/blobstore/71bbff5e70cd3c4ee885125e645b6541527b68acef1621d8d2b7642cf9b8815d/perl-File-Temp-0.231.200-2.amzn2023.0.1.noarch.rpm /pkgs/perl-File-Temp-0.231.200-2.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:20a92ca73b571376767807197722b63bb1b15ade433cdda837e31feacc88a827 https://cdn.amazonlinux.com/al2023/blobstore/20a92ca73b571376767807197722b63bb1b15ade433cdda837e31feacc88a827/perl-File-stat-1.09-477.amzn2023.0.9.noarch.rpm /pkgs/perl-File-stat-1.09-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:0e9cff91bdc4994e5318db43742096a8a506b275531493a32bb0d3fb4ca5f9c7 https://cdn.amazonlinux.com/al2023/blobstore/0e9cff91bdc4994e5318db43742096a8a506b275531493a32bb0d3fb4ca5f9c7/perl-FileHandle-2.03-477.amzn2023.0.9.noarch.rpm /pkgs/perl-FileHandle-2.03-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:1fe9214496235881c15fbeb7ff35b4fc69a72aa6a684031da7895cf136f94526 https://cdn.amazonlinux.com/al2023/blobstore/1fe9214496235881c15fbeb7ff35b4fc69a72aa6a684031da7895cf136f94526/perl-Getopt-Long-2.58-521.amzn2023.0.1.noarch.rpm /pkgs/perl-Getopt-Long-2.58-521.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:a2d2d9dee73a8145db7716c7e6a5373ec64df8d369097f196ca0c1f9293d0e71 https://cdn.amazonlinux.com/al2023/blobstore/a2d2d9dee73a8145db7716c7e6a5373ec64df8d369097f196ca0c1f9293d0e71/perl-Getopt-Std-1.12-477.amzn2023.0.9.noarch.rpm /pkgs/perl-Getopt-Std-1.12-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:f4efe6e89ee5731988c75632afb34f33501fdb15ee18ebfac8573c229e15b6a2 https://cdn.amazonlinux.com/al2023/blobstore/f4efe6e89ee5731988c75632afb34f33501fdb15ee18ebfac8573c229e15b6a2/perl-Git-2.50.1-1.amzn2023.0.1.noarch.rpm /pkgs/perl-Git-2.50.1-1.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:c54ed018789f4542c8c42ce359c8ec93be15b213cbabe8641f8fdbc843eeab71 https://cdn.amazonlinux.com/al2023/blobstore/c54ed018789f4542c8c42ce359c8ec93be15b213cbabe8641f8fdbc843eeab71/perl-HTTP-Tiny-0.092-2.amzn2023.0.2.noarch.rpm /pkgs/perl-HTTP-Tiny-0.092-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:05d828fbde866398408ef1a17bc5fabe1f3d23c02099293a62273619fc3b84a4 https://cdn.amazonlinux.com/al2023/blobstore/05d828fbde866398408ef1a17bc5fabe1f3d23c02099293a62273619fc3b84a4/perl-IO-1.43-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-IO-1.43-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:20cdc381e34496f10affd266bd855603e0b34966273a1929edc60cccc2d05479 https://cdn.amazonlinux.com/al2023/blobstore/20cdc381e34496f10affd266bd855603e0b34966273a1929edc60cccc2d05479/perl-IO-Socket-IP-0.43-522.amzn2023.0.1.noarch.rpm /pkgs/perl-IO-Socket-IP-0.43-522.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:0de0213952bf748d58aa1935d515f3cf77ae5dade378783f77ccef245f934446 https://cdn.amazonlinux.com/al2023/blobstore/0de0213952bf748d58aa1935d515f3cf77ae5dade378783f77ccef245f934446/perl-IO-Socket-SSL-2.075-1.amzn2023.0.3.noarch.rpm /pkgs/perl-IO-Socket-SSL-2.075-1.amzn2023.0.3.noarch.rpm
ADD --checksum=sha256:285d0735f443570fd6a68ba41024d2239bc650e5a09ce9779caf0f6ffca05703 https://cdn.amazonlinux.com/al2023/blobstore/285d0735f443570fd6a68ba41024d2239bc650e5a09ce9779caf0f6ffca05703/perl-IPC-Open3-1.21-477.amzn2023.0.9.noarch.rpm /pkgs/perl-IPC-Open3-1.21-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:d6f3ef66891d771303f9dc7c537d8701f9e7929d098b89ebeb3985e03599e09e https://cdn.amazonlinux.com/al2023/blobstore/d6f3ef66891d771303f9dc7c537d8701f9e7929d098b89ebeb3985e03599e09e/perl-MIME-Base64-3.16-2.amzn2023.0.3.aarch64.rpm /pkgs/perl-MIME-Base64-3.16-2.amzn2023.0.3.aarch64.rpm
ADD --checksum=sha256:da2e4cf0494db0327bc74e014ab069351c4bb1e15a3e611df515ed248cc2ae34 https://cdn.amazonlinux.com/al2023/blobstore/da2e4cf0494db0327bc74e014ab069351c4bb1e15a3e611df515ed248cc2ae34/perl-Net-SSLeay-1.94-3.amzn2023.0.5.aarch64.rpm /pkgs/perl-Net-SSLeay-1.94-3.amzn2023.0.5.aarch64.rpm
ADD --checksum=sha256:55ca2556fd9283b9c35a73c3d3a7344f71312ccc2b49194ff00b37a0869fc799 https://cdn.amazonlinux.com/al2023/blobstore/55ca2556fd9283b9c35a73c3d3a7344f71312ccc2b49194ff00b37a0869fc799/perl-POSIX-1.94-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-POSIX-1.94-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:ac81c67d4629706dfbc07c0ea698b314be6b52314cfdb96dcb1720c350e4b4f0 https://cdn.amazonlinux.com/al2023/blobstore/ac81c67d4629706dfbc07c0ea698b314be6b52314cfdb96dcb1720c350e4b4f0/perl-PathTools-3.78-459.amzn2023.0.3.aarch64.rpm /pkgs/perl-PathTools-3.78-459.amzn2023.0.3.aarch64.rpm
ADD --checksum=sha256:a386219cff753cd97d213c92fe12262dd000dd08e76c4604739139789b28101a https://cdn.amazonlinux.com/al2023/blobstore/a386219cff753cd97d213c92fe12262dd000dd08e76c4604739139789b28101a/perl-Pod-Escapes-1.07-458.amzn2023.0.2.noarch.rpm /pkgs/perl-Pod-Escapes-1.07-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:b3fdf3be498c4ce41189b18365e82378e69ce12b7813fed78a391021aa10f4dd https://cdn.amazonlinux.com/al2023/blobstore/b3fdf3be498c4ce41189b18365e82378e69ce12b7813fed78a391021aa10f4dd/perl-Pod-Perldoc-3.28.01-459.amzn2023.0.3.noarch.rpm /pkgs/perl-Pod-Perldoc-3.28.01-459.amzn2023.0.3.noarch.rpm
ADD --checksum=sha256:999e5ff428f5417f43b965dcb197a2f5d9dbefbfbfc0d108bbccccc2603624dd https://cdn.amazonlinux.com/al2023/blobstore/999e5ff428f5417f43b965dcb197a2f5d9dbefbfbfc0d108bbccccc2603624dd/perl-Pod-Simple-3.42-2.amzn2023.0.2.noarch.rpm /pkgs/perl-Pod-Simple-3.42-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:155757772d960a031bd9cfb1c80b4467cc9a91f91e3696613509e19f4949ede1 https://cdn.amazonlinux.com/al2023/blobstore/155757772d960a031bd9cfb1c80b4467cc9a91f91e3696613509e19f4949ede1/perl-Pod-Usage-2.01-2.amzn2023.0.2.noarch.rpm /pkgs/perl-Pod-Usage-2.01-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:74d7294adeb79ef4c25031800de6b287ee7ee3b702e6a05480b74aebc6d3925d https://cdn.amazonlinux.com/al2023/blobstore/74d7294adeb79ef4c25031800de6b287ee7ee3b702e6a05480b74aebc6d3925d/perl-Scalar-List-Utils-1.56-459.amzn2023.0.3.aarch64.rpm /pkgs/perl-Scalar-List-Utils-1.56-459.amzn2023.0.3.aarch64.rpm
ADD --checksum=sha256:feb38157475d06c6503174483af12a01d808292ff6b475a657faff1116ae9373 https://cdn.amazonlinux.com/al2023/blobstore/feb38157475d06c6503174483af12a01d808292ff6b475a657faff1116ae9373/perl-SelectSaver-1.02-477.amzn2023.0.9.noarch.rpm /pkgs/perl-SelectSaver-1.02-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:202bb8bfe08be57f9cef40e6aaf5415cd635499e94a7158f953621ab76724082 https://cdn.amazonlinux.com/al2023/blobstore/202bb8bfe08be57f9cef40e6aaf5415cd635499e94a7158f953621ab76724082/perl-Socket-2.032-1.amzn2023.0.4.aarch64.rpm /pkgs/perl-Socket-2.032-1.amzn2023.0.4.aarch64.rpm
ADD --checksum=sha256:4dab520b6f1bbb7e2dec4fca71a789a9d59c59a62035aca59d50f3f87472246a https://cdn.amazonlinux.com/al2023/blobstore/4dab520b6f1bbb7e2dec4fca71a789a9d59c59a62035aca59d50f3f87472246a/perl-Storable-3.37-522.amzn2023.0.2.aarch64.rpm /pkgs/perl-Storable-3.37-522.amzn2023.0.2.aarch64.rpm
ADD --checksum=sha256:9ce31d21a9382ae83d826dd28e08e1f28235700c9253f885912a058385054ff7 https://cdn.amazonlinux.com/al2023/blobstore/9ce31d21a9382ae83d826dd28e08e1f28235700c9253f885912a058385054ff7/perl-Symbol-1.08-477.amzn2023.0.9.noarch.rpm /pkgs/perl-Symbol-1.08-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:438a1331f6f9ef4ee91d61cdc81181815f1e4d1b62fe021cb71cd670f8fbe24e https://cdn.amazonlinux.com/al2023/blobstore/438a1331f6f9ef4ee91d61cdc81181815f1e4d1b62fe021cb71cd670f8fbe24e/perl-Term-ANSIColor-5.01-459.amzn2023.0.2.noarch.rpm /pkgs/perl-Term-ANSIColor-5.01-459.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:0311f36e7c4d68dde8f04831e24f6da51f2e889ce9840a7df1aa9118a1c63bea https://cdn.amazonlinux.com/al2023/blobstore/0311f36e7c4d68dde8f04831e24f6da51f2e889ce9840a7df1aa9118a1c63bea/perl-Term-Cap-1.17-458.amzn2023.0.2.noarch.rpm /pkgs/perl-Term-Cap-1.17-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:e302e62cda290d12b86f0e05c99ccf01e7df2bf37aa4661d6af5cbf476e726e8 https://cdn.amazonlinux.com/al2023/blobstore/e302e62cda290d12b86f0e05c99ccf01e7df2bf37aa4661d6af5cbf476e726e8/perl-TermReadKey-2.38-9.amzn2023.0.3.aarch64.rpm /pkgs/perl-TermReadKey-2.38-9.amzn2023.0.3.aarch64.rpm
ADD --checksum=sha256:36a23239257b8caf0ab3d6b869609bf6e5f2b0b35fe233cc995ec2b6bfeb824d https://cdn.amazonlinux.com/al2023/blobstore/36a23239257b8caf0ab3d6b869609bf6e5f2b0b35fe233cc995ec2b6bfeb824d/perl-Text-ParseWords-3.30-458.amzn2023.0.2.noarch.rpm /pkgs/perl-Text-ParseWords-3.30-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:c26b33388c5e1addd19255110a48797eefd23476a911f72338d422c212d0c2d8 https://cdn.amazonlinux.com/al2023/blobstore/c26b33388c5e1addd19255110a48797eefd23476a911f72338d422c212d0c2d8/perl-Text-Tabs%2BWrap-2021.0726-1.amzn2023.0.1.noarch.rpm /pkgs/perl-Text-Tabs+Wrap-2021.0726-1.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:31d3e329b24b97d302fb4297a3ea3caea6615d477e7f483032c9b553f3defb2b https://cdn.amazonlinux.com/al2023/blobstore/31d3e329b24b97d302fb4297a3ea3caea6615d477e7f483032c9b553f3defb2b/perl-Time-HiRes-1.9764-460.amzn2023.0.3.aarch64.rpm /pkgs/perl-Time-HiRes-1.9764-460.amzn2023.0.3.aarch64.rpm
ADD --checksum=sha256:ee39bb8d079e17afe6cfb4114add60c7cee040baf2e4d8aac7bf6c2f8bf5c64a https://cdn.amazonlinux.com/al2023/blobstore/ee39bb8d079e17afe6cfb4114add60c7cee040baf2e4d8aac7bf6c2f8bf5c64a/perl-Time-Local-1.300-5.amzn2023.0.2.noarch.rpm /pkgs/perl-Time-Local-1.300-5.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:71d324651ea6a43c6db2e98cd7f8a6555e8e458d02782ae299c31ccc5c13fb7f https://cdn.amazonlinux.com/al2023/blobstore/71d324651ea6a43c6db2e98cd7f8a6555e8e458d02782ae299c31ccc5c13fb7f/perl-URI-5.18-1.amzn2023.0.1.noarch.rpm /pkgs/perl-URI-5.18-1.amzn2023.0.1.noarch.rpm
ADD --checksum=sha256:715523a90d6bc31a41139412c57dcba8eccfdcc59a1cbc2276228b5b744127b5 https://cdn.amazonlinux.com/al2023/blobstore/715523a90d6bc31a41139412c57dcba8eccfdcc59a1cbc2276228b5b744127b5/perl-base-2.27-477.amzn2023.0.9.noarch.rpm /pkgs/perl-base-2.27-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:b70603ae417a1949a43aa95bd60219d30a81bdb80ef2a379c2fd473c4c19920f https://cdn.amazonlinux.com/al2023/blobstore/b70603ae417a1949a43aa95bd60219d30a81bdb80ef2a379c2fd473c4c19920f/perl-constant-1.33-459.amzn2023.0.2.noarch.rpm /pkgs/perl-constant-1.33-459.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:e9458f5ded25d45e3937165062de73243cccd0fa864eb91fcedd3007aefceb8e https://cdn.amazonlinux.com/al2023/blobstore/e9458f5ded25d45e3937165062de73243cccd0fa864eb91fcedd3007aefceb8e/perl-if-0.60.800-477.amzn2023.0.9.noarch.rpm /pkgs/perl-if-0.60.800-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:8b4a52115dbed2eff5a98e20aa6a13465cd1f223a21a8150cddc66b70477340e https://cdn.amazonlinux.com/al2023/blobstore/8b4a52115dbed2eff5a98e20aa6a13465cd1f223a21a8150cddc66b70477340e/perl-interpreter-5.32.1-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-interpreter-5.32.1-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:1313c68bff3038ed4276122b1af48b8c59d38782b296bd3981cee53a933b3389 https://cdn.amazonlinux.com/al2023/blobstore/1313c68bff3038ed4276122b1af48b8c59d38782b296bd3981cee53a933b3389/perl-lib-0.65-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-lib-0.65-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:9b9ac714d48d9fb3debff9bb4147747cdaf000617cc6f6e59a30ac6ce10e98c6 https://cdn.amazonlinux.com/al2023/blobstore/9b9ac714d48d9fb3debff9bb4147747cdaf000617cc6f6e59a30ac6ce10e98c6/perl-libnet-3.13-2.amzn2023.0.2.noarch.rpm /pkgs/perl-libnet-3.13-2.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:46c1dc742c5daeee286dcc28442d85355475a28f28b9071641c8f7c0b87541b6 https://cdn.amazonlinux.com/al2023/blobstore/46c1dc742c5daeee286dcc28442d85355475a28f28b9071641c8f7c0b87541b6/perl-libs-5.32.1-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-libs-5.32.1-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:d6f203770737a976861c488d2233f29b644e00d3f85eb686b04fb9f5f010a053 https://cdn.amazonlinux.com/al2023/blobstore/d6f203770737a976861c488d2233f29b644e00d3f85eb686b04fb9f5f010a053/perl-mro-1.23-477.amzn2023.0.9.aarch64.rpm /pkgs/perl-mro-1.23-477.amzn2023.0.9.aarch64.rpm
ADD --checksum=sha256:b60facd58b0579eaba5eb8ba6a9d66549f1b25c7eb49fe666fe8c8e52388d7ed https://cdn.amazonlinux.com/al2023/blobstore/b60facd58b0579eaba5eb8ba6a9d66549f1b25c7eb49fe666fe8c8e52388d7ed/perl-overload-1.31-477.amzn2023.0.9.noarch.rpm /pkgs/perl-overload-1.31-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:447c81b47a67c4033165463c6954d02ea5217a6469a27888a219bac63238f783 https://cdn.amazonlinux.com/al2023/blobstore/447c81b47a67c4033165463c6954d02ea5217a6469a27888a219bac63238f783/perl-overloading-0.02-477.amzn2023.0.9.noarch.rpm /pkgs/perl-overloading-0.02-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:af978755a2aec4cb77ba4c7eedd05ce8de99678d8a07552b72435acb2cea89ca https://cdn.amazonlinux.com/al2023/blobstore/af978755a2aec4cb77ba4c7eedd05ce8de99678d8a07552b72435acb2cea89ca/perl-parent-0.238-458.amzn2023.0.2.noarch.rpm /pkgs/perl-parent-0.238-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:24bdbf834529c67dbcfa23901bb315a2e610ba79075590b1e95e949d37a8918c https://cdn.amazonlinux.com/al2023/blobstore/24bdbf834529c67dbcfa23901bb315a2e610ba79075590b1e95e949d37a8918c/perl-podlators-4.14-458.amzn2023.0.2.noarch.rpm /pkgs/perl-podlators-4.14-458.amzn2023.0.2.noarch.rpm
ADD --checksum=sha256:311607ac8ad7d4d1635129bf43595dbb26a31620bf5839dc148e60bf82eb4b69 https://cdn.amazonlinux.com/al2023/blobstore/311607ac8ad7d4d1635129bf43595dbb26a31620bf5839dc148e60bf82eb4b69/perl-subs-1.03-477.amzn2023.0.9.noarch.rpm /pkgs/perl-subs-1.03-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:07b1c37e6e8b836a99fd36e53cf01ad686f325296fae4455efc8742969552867 https://cdn.amazonlinux.com/al2023/blobstore/07b1c37e6e8b836a99fd36e53cf01ad686f325296fae4455efc8742969552867/perl-vars-1.05-477.amzn2023.0.9.noarch.rpm /pkgs/perl-vars-1.05-477.amzn2023.0.9.noarch.rpm
ADD --checksum=sha256:0d5edf982aa8fbab3590a9525865f637ee0888e42a85192424a72dca270956e8 https://cdn.amazonlinux.com/al2023/blobstore/0d5edf982aa8fbab3590a9525865f637ee0888e42a85192424a72dca270956e8/shadow-utils-4.9-12.amzn2023.0.4.aarch64.rpm /pkgs/shadow-utils-4.9-12.amzn2023.0.4.aarch64.rpm
ADD --checksum=sha256:d0aa85e199ae1ba7aa36da43f5cb68b861d8a1bd9f89097356c4c9bc215c98ae https://cdn.amazonlinux.com/al2023/blobstore/d0aa85e199ae1ba7aa36da43f5cb68b861d8a1bd9f89097356c4c9bc215c98ae/systemd-libs-252.23-14.amzn2023.aarch64.rpm /pkgs/systemd-libs-252.23-14.amzn2023.aarch64.rpm
ADD --checksum=sha256:d479f30ce438ab5d91f2a652e60ac5ca00c8662d02ea495477367c1c7d5caca9 https://cdn.amazonlinux.com/al2023/blobstore/d479f30ce438ab5d91f2a652e60ac5ca00c8662d02ea495477367c1c7d5caca9/tar-1.34-1.amzn2023.0.4.aarch64.rpm /pkgs/tar-1.34-1.amzn2023.0.4.aarch64.rpm
ADD --checksum=sha256:c7f712f4ad72709e07c3502a295105cd0fa03d926579529331e6d874a1635ebf https://cdn.amazonlinux.com/al2023/blobstore/c7f712f4ad72709e07c3502a295105cd0fa03d926579529331e6d874a1635ebf/util-linux-2.37.4-1.amzn2023.0.6.aarch64.rpm /pkgs/util-linux-2.37.4-1.amzn2023.0.6.aarch64.rpm
ADD --checksum=sha256:da57659990d3142bcaceaf2ac0c12ed38bee1877b82f280c5f5bd52c766c500a https://cdn.amazonlinux.com/al2023/blobstore/da57659990d3142bcaceaf2ac0c12ed38bee1877b82f280c5f5bd52c766c500a/util-linux-core-2.37.4-1.amzn2023.0.6.aarch64.rpm /pkgs/util-linux-core-2.37.4-1.amzn2023.0.6.aarch64.rpm

FROM amazonlinux:2023@sha256:8ed3c0a996841537f75607e7d1de2114d8150391f75792e8da9268738547e73f AS packages-arm64
ARG SOURCE_DATE_EPOCH
RUN --mount=type=bind,from=pkgs-arm64,source=/pkgs,target=/tmp/factory-pkgs <<'FACTORY_EOF'
set -eu
rpm -Uvh --quiet /tmp/factory-pkgs/*.rpm
rm -rf /var/cache/ldconfig/aux-cache
first=$(ls /tmp/factory-pkgs/*.rpm | head -n 1)
tid=$(rpm -q --qf '%{INSTALLTID}\n' "$(rpm -qp --nosignature --qf '%{NAME}' "$first")" | head -n 1)
for d in /usr/lib/sysimage/rpm /var/lib/rpm; do
  db="$d/rpmdb.sqlite"
  [ -f "$db" ] && [ ! -L "$d" ] || continue
  if [ -n "${SOURCE_DATE_EPOCH:-}" ] && [ "$tid" != "$SOURCE_DATE_EPOCH" ]; then
    python3 - "$db" "$tid" "$SOURCE_DATE_EPOCH" <<'PY'
import sqlite3, struct, sys
db, old, new = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
INSTALLTIME, INSTALLTID, INT32 = 1008, 1128, 4
c = sqlite3.connect(db)
for hnum, blob in c.execute("SELECT hnum, blob FROM Packages").fetchall():
    b = bytearray(blob)
    il = struct.unpack(">I", b[:4])[0]
    data, pos = 8 + il * 16, {}
    for i in range(il):
        tag, typ, off, cnt = struct.unpack(">IIII", b[8 + i * 16:24 + i * 16])
        if tag in (INSTALLTIME, INSTALLTID) and typ == INT32 and cnt == 1:
            pos[tag] = data + off
    if INSTALLTID in pos and struct.unpack(">I", b[pos[INSTALLTID]:pos[INSTALLTID] + 4])[0] == old:
        for p in pos.values():
            b[p:p + 4] = struct.pack(">I", new)
        c.execute("UPDATE Packages SET blob = ? WHERE hnum = ?", (bytes(b), hnum))
c.execute("UPDATE Installtid SET key = ? WHERE key = ?", (struct.pack("<I", new), struct.pack("<I", old)))
c.commit()
c.execute("PRAGMA wal_checkpoint(TRUNCATE)")
c.close()
PY
  fi
  if [ ! -s "$db-wal" ]; then rm -f "$db-wal" "$db-shm"; fi
done
FACTORY_EOF

FROM packages-${TARGETARCH}
COPY --link --from=tool-kubectl /out/ /
LABEL "org.opencontainers.image.description"="Amazon Linux 2023 with git, jq, and kubectl"
LABEL "org.opencontainers.image.source"="https://github.com/northcutted/clearcutt-factory"
LABEL "org.opencontainers.image.vendor"="northcutted"
USER 65532
ENTRYPOINT ["/bin/bash"]
