# syntax=docker/dockerfile:1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e
#
# Code generated by factory from image.yaml and image.lock.yaml. DO NOT EDIT.
# Image: ghcr.io/northcutted/images/platform-tools
#
# Rebuild bit-for-bit with `factory verify`, or directly with BuildKit
# (moby/buildkit:v0.33.1@sha256:cec9f139f45e93c5c69c60f8b07cfad9f43f4ef6b6a6cd917527fea5ff2e3dea):
#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \
#     --opt platform=linux/amd64,linux/arm64 \
#     --opt build-arg:SOURCE_DATE_EPOCH=1791063765 \
#     --output type=oci,dest=image.tar,rewrite-timestamp=true
# from a context staged with `factory render --context-dir`.

ARG TARGETARCH

# ---- tool: kubectl (url 1.37.1, verified: checksum-file) ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-kubectl-amd64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:65691ff77eb6fa44c908b77a1082c9f092c3b9733b5cefabec0d1104890e21a8 https://dl.k8s.io/release/v1.37.1/bin/linux/amd64/kubectl /src/kubectl
RUN install -D -m 0755 /src/kubectl /out/usr/local/bin/kubectl

FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-kubectl-arm64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:ff749f4b78d9c4f1ec87307df9b50119ed819e2094aa9810cb9acffc3286c8c7 https://dl.k8s.io/release/v1.37.1/bin/linux/arm64/kubectl /src/kubectl
RUN install -D -m 0755 /src/kubectl /out/usr/local/bin/kubectl

FROM tool-kubectl-${TARGETARCH} AS tool-kubectl

# ---- tool: helm (url 4.3.0, verified: checksum-file) ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-helm-amd64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:86584a54def73570558f66f5111cc53dfed56689637ae32c1201205d494f54fb https://get.helm.sh/helm-v4.3.0-linux-amd64.tar.gz /src/helm-v4.3.0-linux-amd64.tar.gz
RUN mkdir -p /x && tar -xzf /src/helm-v4.3.0-linux-amd64.tar.gz -C /x \
 && install -D -m 0755 /x/linux-amd64/helm /out/usr/local/bin/helm

FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-helm-arm64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:31c5794dd55c66a51e6b7d2e2ac7a114ae8b1de41ff1d9ba51748ac973b06a08 https://get.helm.sh/helm-v4.3.0-linux-arm64.tar.gz /src/helm-v4.3.0-linux-arm64.tar.gz
RUN mkdir -p /x && tar -xzf /src/helm-v4.3.0-linux-arm64.tar.gz -C /x \
 && install -D -m 0755 /x/linux-arm64/helm /out/usr/local/bin/helm

FROM tool-helm-${TARGETARCH} AS tool-helm

# ---- tool: gh (github-release 2.102.0, verified: checksum-file) ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-gh-amd64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:bb766f710eef8ede859c18578c72c327597cd4c8a85b06001b1f3843c6019386 https://github.com/cli/cli/releases/download/v2.102.0/gh_2.102.0_linux_amd64.tar.gz /src/gh_2.102.0_linux_amd64.tar.gz
RUN mkdir -p /x && tar -xzf /src/gh_2.102.0_linux_amd64.tar.gz -C /x \
 && install -D -m 0755 /x/gh_2.102.0_linux_amd64/bin/gh /out/usr/local/bin/gh

FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-gh-arm64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:7862c86c72f43df3a2d93ddde6f473285b4e2af61b494849846827e513ef6484 https://github.com/cli/cli/releases/download/v2.102.0/gh_2.102.0_linux_arm64.tar.gz /src/gh_2.102.0_linux_arm64.tar.gz
RUN mkdir -p /x && tar -xzf /src/gh_2.102.0_linux_arm64.tar.gz -C /x \
 && install -D -m 0755 /x/gh_2.102.0_linux_arm64/bin/gh /out/usr/local/bin/gh

FROM tool-gh-${TARGETARCH} AS tool-gh

# ---- tool: cosign (github-release 3.1.3, verified: github-asset-digest) ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-cosign-amd64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:4629c757b7618056f8ddd7e2625ae9fdd94c0372a65049520bc7d9df9efc7f71 https://github.com/sigstore/cosign/releases/download/v3.1.3/cosign-linux-amd64 /src/cosign-linux-amd64
RUN install -D -m 0755 /src/cosign-linux-amd64 /out/usr/local/bin/cosign

FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS tool-cosign-arm64
ARG SOURCE_DATE_EPOCH
ADD --checksum=sha256:c5d324e091826b0d7a78eb16fef316450b4eb9aaec045611c08ba06f5e73220a https://github.com/sigstore/cosign/releases/download/v3.1.3/cosign-linux-arm64 /src/cosign-linux-arm64
RUN install -D -m 0755 /src/cosign-linux-arm64 /out/usr/local/bin/cosign

FROM tool-cosign-${TARGETARCH} AS tool-cosign

# ---- tool: crane (oci, verified: image-digest) ----
# copied straight from gcr.io/go-containerregistry/crane:latest@sha256:1f968817b95790bed063f71175aa6b8ff879fa17064020415f3e18bb6e6a36e1

# ---- tool: yq (go v4.54.1, verified: go-sumdb) ----
FROM --platform=$BUILDPLATFORM golang:1@sha256:e0174e51e81218523251d85d248a90d24c3d5e81543b4f07a5d66229397db190 AS tool-yq
ARG TARGETOS TARGETARCH SOURCE_DATE_EPOCH
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH GOFLAGS=-trimpath \
    go install -ldflags='-s -w -buildid=' github.com/mikefarah/yq/v4@v4.54.1 \
 && install -D -m 0755 "$(find /go/bin -type f | head -n 1)" /out/usr/local/bin/yq

# ---- files ----
FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03 AS files
ARG SOURCE_DATE_EPOCH
COPY files/0/ /in/0/
RUN mkdir -p /out/etc/platform-tools && cp -R /in/0/. /out/etc/platform-tools/

# ---- image ----
FROM cgr.dev/chainguard/wolfi-base:latest@sha256:9c2092b053779e14c82fb50f77b37bcc38b7d2c83972352d5813280f9d035b03
ARG SOURCE_DATE_EPOCH
RUN apk add --no-cache --repositories-file /dev/null \
      --repository https://apk.cgr.dev/chainguard \
      apk-tools=2.14.10-r17 \
      bash=5.3-r13 \
      busybox=1.38.0-r2 \
      ca-certificates-bundle=20260909-r2 \
      curl=8.22.0-r4 \
      cyrus-sasl-heimdal-libs=2.1.28-r58 \
      gdbm=1.26-r6 \
      git=2.55.0-r10 \
      glibc-2.44=2.44-r7 \
      glibc-2.44-locale-posix=2.44-r7 \
      heimdal-libs=7.8.0-r52 \
      jq=1.8.2-r2 \
      keyutils-libs=1.6.3-r40 \
      krb5-conf=1.0-r9 \
      krb5-libs=1.22.2-r4 \
      ld-linux-2.44=2.44-r7 \
      libbrotlicommon1=1.2.0-r5 \
      libbrotlidec1=1.2.0-r5 \
      libbrotlienc1=1.2.0-r5 \
      libcom_err=1.47.4-r2 \
      libcrypt1-2.44=2.44-r7 \
      libcrypto3=3.6.5-r1 \
      libcurl-openssl4=8.22.0-r4 \
      libexpat1=2.8.5-r0 \
      libgcc=16.2.0-r1 \
      libidn2=2.3.8-r9 \
      libldap=2.6.10-r5 \
      libnghttp2-14=1.70.0-r5 \
      libpcre2-8-0=10.49-r1 \
      libpsl=0.23.3-r1 \
      libssl3=3.6.5-r1 \
      libunistring=1.4.2-r3 \
      libverto=0.3.2-r8 \
      libxcrypt=4.5.2-r5 \
      ncurses=6.6.20260926-r0 \
      ncurses-terminfo-base=6.6.20260926-r0 \
      nghttp3=1.18.0-r1 \
      ngtcp2=1.25.0-r5 \
      oniguruma=6.9.10-r5 \
      openssl-4.0-libcrypto=4.0.3-r2 \
      openssl-4.0-libssl=4.0.3-r2 \
      openssl-provider-legacy-allowed=4.0.2-r3 \
      readline=8.3-r3 \
      sqlite-libs=3.53.4-r2 \
      wolfi-base=1-r7 \
      wolfi-baselayout=20230201-r30 \
      wolfi-keys=1-r13 \
      zlib=1.3.2.1_rc20260601-r0 \
 && rm -f /var/cache/ldconfig/aux-cache
COPY --link --from=tool-kubectl /out/ /
COPY --link --from=tool-helm /out/ /
COPY --link --from=tool-gh /out/ /
COPY --link --from=tool-cosign /out/ /
COPY --link --from=gcr.io/go-containerregistry/crane:latest@sha256:1f968817b95790bed063f71175aa6b8ff879fa17064020415f3e18bb6e6a36e1 /ko-app/crane /usr/local/bin/crane
COPY --link --from=tool-yq /out/ /
COPY --link --from=files /out/ /
ENV KUBECONFIG="/home/nonroot/.kube/config"
LABEL "org.opencontainers.image.description"="kubectl, helm, gh, cosign, crane, and yq on Wolfi"
LABEL "org.opencontainers.image.source"="https://github.com/northcutted/declarative-image-factory"
LABEL "org.opencontainers.image.vendor"="northcutted"
USER 65532
WORKDIR /home/nonroot
ENTRYPOINT ["/bin/bash"]
