# syntax=docker/dockerfile:1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e
#
# Code generated by factory from app.yaml and app.lock.yaml. DO NOT EDIT.
# Image: ghcr.io/northcutted/images/hello-app (app hello-app on stack go)
#
# Rebuild bit-for-bit with `clearcutt-factory verify`, or directly with BuildKit
# (moby/buildkit:v0.33.1@sha256:cec9f139f45e93c5c69c60f8b07cfad9f43f4ef6b6a6cd917527fea5ff2e3dea):
#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \
#     --opt platform=linux/amd64,linux/arm64 \
#     --opt build-arg:SOURCE_DATE_EPOCH=1791504000 \
#     --output type=oci,dest=image.tar,rewrite-timestamp=true,$ANNOTATIONS
# from a context staged with `clearcutt-factory render --context-dir`, where
# $ANNOTATIONS (comma-separated) records the base for `clearcutt-factory rebase`:
#   annotation-manifest[linux/amd64].org.opencontainers.image.base.name=cgr.dev/chainguard/static:latest
#   annotation-manifest[linux/amd64].org.opencontainers.image.base.digest=sha256:a40219f3b0c2719e4e4220310e80a2230a4b95881644292c130e3a8e8287fc6c
#   annotation-manifest[linux/arm64].org.opencontainers.image.base.name=cgr.dev/chainguard/static:latest
#   annotation-manifest[linux/arm64].org.opencontainers.image.base.digest=sha256:daed076c904e5dc26f5ff87d77aa4cea8b7ca76e906b561915dafe5b086377dc

ARG TARGETARCH

# ---- build: stack go ----
FROM --platform=$BUILDPLATFORM golang:1@sha256:e432b43af23a9328d56a7c499be0476810aa344acbcf65fc7c455d4ff5a40602 AS build
ARG TARGETOS TARGETARCH SOURCE_DATE_EPOCH
ENV APP_NAME="hello-app"
ENV CGO_ENABLED="0"
ENV MAIN="."
WORKDIR /src
COPY src/ /src/
RUN --mount=type=cache,target=/root/.cache/go-build,id=/root/.cache/go-build,sharing=locked --mount=type=cache,target=/go/pkg/mod,id=/go/pkg/mod,sharing=locked <<'FACTORY_EOF'
set -eu
mkdir -p /out
go mod download
FACTORY_EOF
RUN --mount=type=cache,target=/root/.cache/go-build,id=/root/.cache/go-build,sharing=locked --mount=type=cache,target=/go/pkg/mod,id=/go/pkg/mod,sharing=locked <<'FACTORY_EOF'
set -eu
GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -ldflags="-s -w -buildid=" -o "/out/$APP_NAME" "$MAIN"
FACTORY_EOF

# ---- app ----
FROM cgr.dev/chainguard/static:latest@sha256:fe55470f22d3259488d9d3739168d8f04da67755f0b69382bc26eda4a7d3d327
COPY --link --from=build /out/ /app/
ENV PORT="8080"
LABEL "org.opencontainers.image.description"="A tiny HTTP service built on the go stack"
LABEL "org.opencontainers.image.source"="https://github.com/northcutted/clearcutt-factory"
LABEL "org.opencontainers.image.vendor"="northcutted"
USER 65532
ENTRYPOINT ["/app/hello-app"]
