// Package render generates a Containerfile from a manifest and its lock. The
// output only references pinned inputs, so it is the reproducibility artifact:
// anyone with the same BuildKit can rebuild the exact image from it.
package render

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/northcutted/declarative-image-factory/internal/lock"
	"github.com/northcutted/declarative-image-factory/internal/manifest"
	"github.com/northcutted/declarative-image-factory/internal/nix"
	"github.com/northcutted/declarative-image-factory/internal/rebase"
	"github.com/northcutted/declarative-image-factory/internal/registry"
)

// ContainerfileName is the Containerfile's name inside a staged build context.
const ContainerfileName = "Containerfile"

// Output is a rendered build: the Containerfile plus the local files the build
// context must contain.
type Output struct {
	Containerfile []byte
	Context       []ContextFile
	// Annotations are BuildKit output options (annotation-manifest[…].key=value)
	// the build must pass; apps record their base this way.
	Annotations []string
}

// ContextFile maps a local path into the staged build context.
type ContextFile struct {
	Src string // absolute local path (file or directory)
	Rel string // path inside the context, slash-separated
	// Exclude lists paths below a directory Src to leave out, in
	// .gitignore style: a slash at the start or in the middle anchors a
	// pattern to Src, otherwise it matches a name at any depth.
	Exclude []string
}

// Render produces the Containerfile for m pinned by l.
func Render(m *manifest.Manifest, l *lock.Lock) (*Output, error) {
	r := &renderer{m: m, l: l}
	if m.Kind == manifest.KindApp {
		return r.renderApp()
	}
	return r.render()
}

type renderer struct {
	m   *manifest.Manifest
	l   *lock.Lock
	b   bytes.Buffer
	out Output
}

func (r *renderer) f(format string, a ...any) { fmt.Fprintf(&r.b, format, a...) }

func (r *renderer) render() (*Output, error) {
	m, l := r.m, r.l
	r.f("# syntax=%s\n", l.Builder.Frontend.Pinned())
	r.f("#\n# Code generated by factory from %s and %s. DO NOT EDIT.\n", filepath.Base(m.Path), filepath.Base(m.LockPath()))
	r.f("# Image: %s\n#\n", m.Metadata.Ref)
	r.f("# Rebuild bit-for-bit with `factory verify`, or directly with BuildKit\n# (%s):\n", l.Builder.BuildKit.Pinned())
	r.f("#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \\\n")
	r.f("#     --opt platform=%s \\\n", strings.Join(m.Spec.Platforms, ","))
	r.f("#     --opt build-arg:SOURCE_DATE_EPOCH=%d \\\n", l.SourceDateEpoch)
	r.f("#     --output type=oci,dest=image.tar,rewrite-timestamp=true\n")
	r.f("# from a context staged with `factory render --context-dir`.\n\n")
	r.f("ARG TARGETARCH\n")

	var copies []string
	var nixTools []manifest.Tool
	for _, t := range m.Spec.Tools {
		if t.From == manifest.FromNix {
			nixTools = append(nixTools, t)
		}
	}
	nixDone := false
	for _, t := range m.Spec.Tools {
		lt := l.Tool(t.Name)
		if lt == nil || lt.SpecDigest != lock.Digest(t) {
			return nil, fmt.Errorf("tool %s is not locked or changed since locking; run factory lock", t.Name)
		}
		if t.From == manifest.FromNix {
			// All nix tools share one store copy, placed at the first one.
			if nixDone {
				continue
			}
			nixDone = true
			c, err := r.nix(nixTools)
			if err != nil {
				return nil, err
			}
			copies = append(copies, c)
			continue
		}
		c, err := r.tool(t, lt)
		if err != nil {
			return nil, fmt.Errorf("tool %s: %w", t.Name, err)
		}
		copies = append(copies, c)
	}
	if len(m.Spec.Files) > 0 {
		c, err := r.files()
		if err != nil {
			return nil, err
		}
		copies = append(copies, c)
	}

	r.f("\n# ---- image ----\n")
	if err := r.packages(); err != nil {
		return nil, err
	}
	for _, c := range copies {
		r.f("%s\n", c)
	}
	r.config()
	r.out.Containerfile = r.b.Bytes()
	return &r.out, nil
}

func (r *renderer) tool(t manifest.Tool, lt *lock.Tool) (string, error) {
	stage := "tool-" + t.Name
	dest := t.Dest
	if dest == "" {
		dest = "/usr/local/bin/" + t.Name
	}
	mode := normMode(t.Mode, "0755")
	r.f("\n# ---- tool: %s (%s", t.Name, t.From)
	if lt.Version != "" {
		r.f(" %s", lt.Version)
	}
	r.f(", verified: %s) ----\n", lt.Verification)

	switch t.From {
	case manifest.FromURL, manifest.FromGitHubRelease:
		byArch := map[string]lock.Artifact{}
		var arches []string
		for _, p := range r.m.Spec.Platforms {
			a, ok := lt.Artifacts[p]
			if !ok {
				return "", fmt.Errorf("no locked artifact for %s; run factory lock", p)
			}
			_, arch, _ := manifest.SplitPlatform(p)
			byArch[arch] = a
			arches = append(arches, arch)
		}
		if allSame(byArch) {
			if err := r.fetchStage(stage, byArch[arches[0]], dest, mode); err != nil {
				return "", err
			}
		} else {
			for _, arch := range arches {
				if err := r.fetchStage(stage+"-"+arch, byArch[arch], dest, mode); err != nil {
					return "", err
				}
				r.f("\n")
			}
			r.f("FROM %s-${TARGETARCH} AS %s\n", stage, stage)
		}
		return fmt.Sprintf("COPY --link --from=%s /out/ /", stage), nil

	case manifest.FromOCI:
		chmod := ""
		if t.Mode != "" {
			chmod = " --chmod=" + mode
		}
		r.f("# copied straight from %s\n", lt.Image.Pinned())
		return fmt.Sprintf("COPY --link%s --from=%s %s %s", chmod, lt.Image.Pinned(), t.Path, dest), nil

	case manifest.FromGo:
		r.f("FROM --platform=$BUILDPLATFORM %s AS %s\n", lt.Image.Pinned(), stage)
		r.f("ARG TARGETOS TARGETARCH %s\n", strings.TrimPrefix(epochArg, "ARG "))
		r.f("RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \\\n")
		r.f("    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH GOFLAGS=-trimpath \\\n")
		r.f("    go install -ldflags='-s -w -buildid=' %s@%s \\\n", t.Package, lt.Version)
		r.f(" && install -D -m %s \"$(find /go/bin -type f | head -n 1)\" %s\n", mode, shq("/out"+dest))
		return fmt.Sprintf("COPY --link --from=%s /out/ /", stage), nil

	case manifest.FromBuild:
		r.f("# runs on the target platform; everything written to /out is copied into the image\n")
		r.f("FROM %s AS %s\n", lt.Image.Pinned(), stage)
		r.f("%s\n", epochArg)
		r.f("RUN <<'FACTORY_EOF'\nset -eu\nmkdir -p /out\n%s\nFACTORY_EOF\n", strings.TrimRight(t.Run, "\n"))
		return fmt.Sprintf("COPY --link --from=%s /out/ /", stage), nil
	}
	return "", fmt.Errorf("unknown source %q", t.From)
}

// fetchStage downloads a checksummed artifact and installs it under /out. The
// copy into /out gives every file a fresh mtime that rewrite-timestamp clamps,
// so upstream Last-Modified headers and archive mtimes never reach the image.
func (r *renderer) fetchStage(stage string, a lock.Artifact, dest, mode string) error {
	file := path.Base(a.URL)
	if i := strings.IndexAny(file, "?#"); i >= 0 {
		file = file[:i]
	}
	if strings.ContainsAny(a.URL, " \t\n") {
		return fmt.Errorf("URL contains whitespace: %q", a.URL)
	}
	src := "/src/" + file
	r.f("FROM --platform=$BUILDPLATFORM %s AS %s\n", r.l.Builder.Toolbox.Pinned(), stage)
	r.f("%s\n", epochArg)
	r.f("ADD --checksum=sha256:%s %s %s\n", a.SHA256, r.url(a.URL), src)
	if a.Extract == "" {
		r.f("RUN install -D -m %s %s %s\n", mode, shq(src), shq("/out"+dest))
		return nil
	}
	unpack, err := unpackCmd(file, src)
	if err != nil {
		return err
	}
	r.f("RUN mkdir -p /x && %s \\\n && install -D -m %s %s %s\n", unpack, mode, shq(path.Join("/x", a.Extract)), shq("/out"+dest))
	return nil
}

func unpackCmd(file, src string) (string, error) {
	switch {
	case strings.HasSuffix(file, ".tar.gz"), strings.HasSuffix(file, ".tgz"):
		return "tar -xzf " + shq(src) + " -C /x", nil
	case strings.HasSuffix(file, ".tar.xz"), strings.HasSuffix(file, ".txz"):
		return "tar -xJf " + shq(src) + " -C /x", nil
	case strings.HasSuffix(file, ".tar.bz2"), strings.HasSuffix(file, ".tbz2"):
		return "tar -xjf " + shq(src) + " -C /x", nil
	case strings.HasSuffix(file, ".tar"):
		return "tar -xf " + shq(src) + " -C /x", nil
	case strings.HasSuffix(file, ".zip"):
		return "unzip -q " + shq(src) + " -d /x", nil
	}
	return "", fmt.Errorf("extract: don't know how to unpack %s (supported: .tar[.gz|.xz|.bz2], .tgz, .zip)", file)
}

// files stages local files through the toolbox so their mtimes are reset.
func (r *renderer) files() (string, error) {
	r.f("\n# ---- files ----\n")
	r.f("FROM --platform=$BUILDPLATFORM %s AS files\n", r.l.Builder.Toolbox.Pinned())
	r.f("%s\n", epochArg)
	var cmds []string
	for i, f := range r.m.Spec.Files {
		st, err := os.Stat(f.AbsSrc)
		if err != nil {
			return "", err
		}
		in := fmt.Sprintf("/in/%d", i)
		if st.IsDir() {
			rel := fmt.Sprintf("files/%d", i)
			r.out.Context = append(r.out.Context, ContextFile{Src: f.AbsSrc, Rel: rel})
			r.f("COPY %s/ %s/\n", rel, in)
			dst := "/out" + strings.TrimSuffix(f.Dst, "/")
			cmd := fmt.Sprintf("mkdir -p %s && cp -R %s/. %s/", shq(dst), in, shq(dst))
			if f.Mode != "" {
				cmd += fmt.Sprintf(" && find %s -type f -exec chmod %s {} +", shq(dst), normMode(f.Mode, ""))
			}
			cmds = append(cmds, cmd)
			continue
		}
		name := filepath.Base(f.AbsSrc)
		rel := fmt.Sprintf("files/%d/%s", i, name)
		r.out.Context = append(r.out.Context, ContextFile{Src: f.AbsSrc, Rel: rel})
		r.f("COPY %s\n", copyArgs(rel, in+"/"+name))
		dst := f.Dst
		if strings.HasSuffix(dst, "/") {
			dst += name
		}
		cmds = append(cmds, fmt.Sprintf("install -D -m %s %s %s", normMode(f.Mode, "0644"), shq(in+"/"+name), shq("/out"+dst)))
	}
	r.f("RUN %s\n", strings.Join(cmds, " \\\n && "))
	return "COPY --link --from=files /out/ /", nil
}

func (r *renderer) packages() error {
	base := r.l.Base.Pinned()
	if len(r.m.Spec.Packages) == 0 {
		r.f("FROM %s\n", base)
		return nil
	}
	pk := r.l.Packages
	if len(pk.Platforms) == 0 {
		return fmt.Errorf("packages are not locked; run factory lock")
	}
	if pk.EffectiveManager() != lock.ManagerAPK {
		return r.nativePackages()
	}
	sets := map[string][]string{}
	var arches []string
	for _, p := range r.m.Spec.Platforms {
		pkgs, ok := pk.Platforms[p]
		if !ok {
			return fmt.Errorf("packages for %s are not locked; run factory lock", p)
		}
		_, arch, _ := manifest.SplitPlatform(p)
		arches = append(arches, arch)
		for _, x := range pkgs {
			sets[arch] = append(sets[arch], x.Name+"="+x.Version)
		}
	}
	same := true
	for _, a := range arches[1:] {
		same = same && slices.Equal(sets[a], sets[arches[0]])
	}
	if same {
		r.f("FROM %s\n", base)
		r.apkAdd(sets[arches[0]])
		return nil
	}
	for _, a := range arches {
		r.f("FROM %s AS packages-%s\n", base, a)
		r.apkAdd(sets[a])
		r.f("\n")
	}
	r.f("FROM packages-${TARGETARCH}\n")
	return nil
}

// epochArg is declared in every stage that runs commands. It puts the epoch in
// RUN cache keys: a layer cached under an older epoch would carry file times
// below the new one, which rewrite-timestamp does not clamp.
const epochArg = "ARG SOURCE_DATE_EPOCH"

// apkAdd installs exactly the locked set. glibc's ldconfig aux-cache records
// inode numbers and timestamps, so it is removed to keep the layer reproducible.
func (r *renderer) apkAdd(pins []string) {
	r.f("%s\n", epochArg)
	r.f("RUN apk add --no-cache --repositories-file /dev/null \\\n")
	for _, repo := range r.l.Packages.Repositories {
		r.f("      --repository %s \\\n", r.url(repo))
	}
	for _, p := range pins {
		r.f("      %s \\\n", p)
	}
	r.f(" && rm -f /var/cache/ldconfig/aux-cache\n")
}

func (r *renderer) config() {
	s := r.m.Spec
	for _, k := range sortedKeys(s.Env) {
		r.f("ENV %s=%s\n", k, dq(s.Env[k]))
	}
	for _, k := range sortedKeys(s.Labels) {
		r.f("LABEL %s=%s\n", dq(k), dq(s.Labels[k]))
	}
	if s.User != "" {
		r.f("USER %s\n", s.User)
	}
	if s.Workdir != "" {
		r.f("WORKDIR %s\n", s.Workdir)
	}
	if len(s.Entrypoint) > 0 {
		r.f("ENTRYPOINT %s\n", jsonArray(s.Entrypoint))
	}
	if len(s.Cmd) > 0 {
		r.f("CMD %s\n", jsonArray(s.Cmd))
	}
}

// nativeInstall is how each manager installs a directory of pinned package
// files offline, and what it leaves behind that differs between runs.
var nativeInstall = map[string]struct{ ext, install, cleanup string }{
	lock.ManagerAPT: {
		ext:     ".deb",
		install: "DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends /tmp/factory-pkgs/*.deb",
		cleanup: "rm -rf /var/lib/apt/lists/* /var/cache/apt/*.bin /var/log/apt/* /var/log/dpkg.log /var/log/alternatives.log" +
			" /var/cache/ldconfig/aux-cache /var/cache/debconf/*-old /var/lib/dpkg/*-old",
	},
	lock.ManagerDNF: {ext: ".rpm"}, // installed by rpmInstallScript
}

// rpmInstallScript installs the pinned RPMs and makes the rpm database
// reproducible: rpm 4.16 without the SOURCE_DATE_EPOCH backport (Amazon Linux)
// stamps INSTALLTIME/INSTALLTID with the wall clock, so those values are
// rewritten to the epoch in the headers (outside their signed region) and the
// Installtid index; SQLite's shared-memory file holds random salts and is
// removed once the write-ahead log is empty.
const rpmInstallScript = `set -eu
rpm -Uvh --quiet /tmp/factory-pkgs/*.rpm
rm -rf /var/cache/ldconfig/aux-cache
first=$(ls /tmp/factory-pkgs/*.rpm | head -n 1)
tid=$(rpm -q --qf '%{INSTALLTID}\n' "$(rpm -qp --nosignature --qf '%{NAME}' "$first")" | head -n 1)
for d in /usr/lib/sysimage/rpm /var/lib/rpm; do
  db="$d/rpmdb.sqlite"
  [ -f "$db" ] && [ ! -L "$d" ] || continue
  if [ -n "${SOURCE_DATE_EPOCH:-}" ] && [ "$tid" != "$SOURCE_DATE_EPOCH" ]; then
    python3 - "$db" "$tid" "$SOURCE_DATE_EPOCH" <<'PY'
import sqlite3, struct, sys
db, old, new = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
INSTALLTIME, INSTALLTID, INT32 = 1008, 1128, 4
c = sqlite3.connect(db)
for hnum, blob in c.execute("SELECT hnum, blob FROM Packages").fetchall():
    b = bytearray(blob)
    il = struct.unpack(">I", b[:4])[0]
    data, pos = 8 + il * 16, {}
    for i in range(il):
        tag, typ, off, cnt = struct.unpack(">IIII", b[8 + i * 16:24 + i * 16])
        if tag in (INSTALLTIME, INSTALLTID) and typ == INT32 and cnt == 1:
            pos[tag] = data + off
    if INSTALLTID in pos and struct.unpack(">I", b[pos[INSTALLTID]:pos[INSTALLTID] + 4])[0] == old:
        for p in pos.values():
            b[p:p + 4] = struct.pack(">I", new)
        c.execute("UPDATE Packages SET blob = ? WHERE hnum = ?", (bytes(b), hnum))
c.execute("UPDATE Installtid SET key = ? WHERE key = ?", (struct.pack("<I", new), struct.pack("<I", old)))
c.commit()
c.execute("PRAGMA wal_checkpoint(TRUNCATE)")
c.close()
PY
  fi
  if [ ! -s "$db-wal" ]; then rm -f "$db-wal" "$db-shm"; fi
done`

// nativePackages downloads the locked .deb/.rpm files (each checked against
// its sha256) and installs exactly those, without contacting a repository.
func (r *renderer) nativePackages() error {
	pk := r.l.Packages
	how := nativeInstall[pk.Manager]
	if how.ext == "" {
		return fmt.Errorf("unknown package manager %q", pk.Manager)
	}
	base := r.l.Base.Pinned()
	r.f("# packages: %s (%s", pk.Manager, pk.Distro)
	if pk.Snapshot != "" {
		r.f(", snapshot %s", pk.Snapshot)
	}
	r.f(")\n")
	for _, p := range r.m.Spec.Platforms {
		pkgs, ok := pk.Platforms[p]
		if !ok {
			return fmt.Errorf("packages for %s are not locked; run factory lock", p)
		}
		_, arch, _ := manifest.SplitPlatform(p)
		if len(pkgs) == 0 {
			r.f("FROM %s AS packages-%s\n\n", base, arch)
			continue
		}
		r.f("FROM scratch AS pkgs-%s\n", arch)
		for _, x := range pkgs {
			if x.SHA256 == "" || x.URL == "" || x.Filename == "" || strings.ContainsAny(x.Filename, "/ ") {
				return fmt.Errorf("package %s %s has no usable URL, filename, or sha256 in the lock; run factory lock --update", x.Name, x.Version)
			}
			r.f("ADD --checksum=sha256:%s %s /pkgs/%s\n", x.SHA256, r.url(x.URL), x.Filename)
		}
		r.f("\nFROM %s AS packages-%s\n", base, arch)
		r.f("%s\n", epochArg)
		mount := fmt.Sprintf("--mount=type=bind,from=pkgs-%s,source=/pkgs,target=/tmp/factory-pkgs", arch)
		if pk.Manager == lock.ManagerDNF {
			r.f("RUN %s <<'FACTORY_EOF'\n%s\nFACTORY_EOF\n\n", mount, rpmInstallScript)
			continue
		}
		r.f("RUN %s \\\n", mount)
		r.f("    %s \\\n && %s\n\n", how.install, how.cleanup)
	}
	r.f("FROM packages-${TARGETARCH}\n")
	return nil
}

// nix copies the locked store paths of every nix tool, with their closures,
// from the binary cache (which checks each path's signature) and links their
// binaries into /usr/local/bin. Store files carry fixed timestamps and modes.
func (r *renderer) nix(tools []manifest.Tool) (string, error) {
	var image string
	var names []string
	for _, t := range tools {
		lt := r.l.Tool(t.Name)
		if image == "" {
			image = lt.Image.Pinned()
		} else if lt.Image.Pinned() != image {
			return "", fmt.Errorf("nix tools must share one nix image; %s uses %s", t.Name, lt.Image.Pinned())
		}
		names = append(names, fmt.Sprintf("%s %s", t.Name, lt.Version))
	}
	r.f("\n# ---- nix: %s (verified: %s) ----\n", strings.Join(names, ", "), lock.VerifiedNixSignature)
	for _, p := range r.m.Spec.Platforms {
		_, arch, _ := manifest.SplitPlatform(p)
		var paths []string
		for _, t := range tools {
			out, ok := r.l.Tool(t.Name).Nix[p]
			if !ok {
				return "", fmt.Errorf("tool %s has no store path for %s; run factory lock", t.Name, p)
			}
			paths = append(paths, out.Path)
		}
		list := strings.Join(paths, " \\\n      ")
		r.f("FROM --platform=$BUILDPLATFORM %s AS nix-%s\n", image, arch)
		r.f("%s\n", epochArg)
		r.f("RUN nix --extra-experimental-features nix-command copy --from %s \\\n      %s \\\n", r.url(nix.DefaultCache), list)
		r.f(" && mkdir -p /out/nix/store /out/usr/local/bin \\\n")
		r.f(" && cp -a $(nix-store --query --requisites %s) /out/nix/store/ \\\n", strings.Join(paths, " "))
		r.f(" && for p in %s; do for b in \"$p\"/bin/*; do if [ -e \"$b\" ]; then ln -sf \"$b\" /out/usr/local/bin/; fi; done; done\n\n", strings.Join(paths, " "))
	}
	r.f("FROM nix-${TARGETARCH} AS nix\n")
	return "COPY --link --from=nix /out/ /", nil
}

// DefaultExclude is left out of every app's source.
var DefaultExclude = []string{".git", "/out"}

// renderApp builds the app with its stack's steps in the build image, then
// copies only /out onto the run image. COPY --link makes that layer
// independent of the run image, so the app can later be rebased onto a new
// build of it.
func (r *renderer) renderApp() (*Output, error) {
	m, l := r.m, r.l
	st := m.Stack
	if l.App == nil || l.App.StackDigest != lock.StackDigest(st) || l.App.Build.Ref != st.BuildRef {
		return nil, fmt.Errorf("the stack is not locked or changed since locking; run factory lock")
	}
	baseName := registry.Qualify(l.Base.Ref)
	for _, p := range m.Spec.Platforms {
		d := l.App.RunPlatforms[p]
		if d == "" {
			return nil, fmt.Errorf("no run image digest for %s in the lock; run factory lock", p)
		}
		// BuildKit only applies platform-qualified annotations to
		// multi-platform builds.
		key := "annotation-manifest"
		if len(m.Spec.Platforms) > 1 {
			key += "[" + p + "]"
		}
		r.out.Annotations = append(r.out.Annotations,
			fmt.Sprintf("%s.%s=%s", key, rebase.AnnotationBaseName, baseName),
			fmt.Sprintf("%s.%s=%s", key, rebase.AnnotationBaseDigest, d))
	}

	r.f("# syntax=%s\n", l.Builder.Frontend.Pinned())
	r.f("#\n# Code generated by factory from %s and %s. DO NOT EDIT.\n", filepath.Base(m.Path), filepath.Base(m.LockPath()))
	r.f("# Image: %s (app %s on stack %s)\n#\n", m.Metadata.Ref, m.Metadata.Name, st.Metadata.Name)
	r.f("# Rebuild bit-for-bit with `factory verify`, or directly with BuildKit\n# (%s):\n", l.Builder.BuildKit.Pinned())
	r.f("#   buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. \\\n")
	r.f("#     --opt platform=%s \\\n", strings.Join(m.Spec.Platforms, ","))
	r.f("#     --opt build-arg:SOURCE_DATE_EPOCH=%d \\\n", l.SourceDateEpoch)
	r.f("#     --output type=oci,dest=image.tar,rewrite-timestamp=true,$ANNOTATIONS\n")
	r.f("# from a context staged with `factory render --context-dir`, where\n")
	r.f("# $ANNOTATIONS (comma-separated) records the base for `factory rebase`:\n")
	for _, a := range r.out.Annotations {
		r.f("#   %s\n", a)
	}
	r.f("\nARG TARGETARCH\n")

	r.f("\n# ---- build: stack %s ----\n", st.Metadata.Name)
	from := ""
	if st.Spec.CrossCompile {
		from = "--platform=$BUILDPLATFORM "
	}
	r.f("FROM %s%s AS build\n", from, l.App.Build.Pinned())
	r.f("ARG TARGETOS TARGETARCH %s\n", strings.TrimPrefix(epochArg, "ARG "))
	env := map[string]string{"APP_NAME": m.Metadata.Name}
	for k, v := range m.Spec.BuildEnv {
		env[k] = v
	}
	for _, k := range sortedKeys(env) {
		r.f("ENV %s=%s\n", k, dq(env[k]))
	}
	r.f("WORKDIR /src\n")
	r.f("COPY src/ /src/\n")
	r.out.Context = append(r.out.Context, ContextFile{
		Src: m.Spec.SourceDir, Rel: "src", Exclude: append(slices.Clone(DefaultExclude), m.Spec.Exclude...),
	})
	var mounts []string
	for _, c := range st.Spec.Caches {
		id := c
		if !st.Spec.CrossCompile {
			id += "-$TARGETARCH" // caches may hold platform-specific builds
		}
		mounts = append(mounts, fmt.Sprintf("--mount=type=cache,target=%s,id=%s,sharing=locked", c, id))
	}
	mount := strings.Join(mounts, " ")
	if mount != "" {
		mount += " "
	}
	for i := range st.Spec.Steps {
		prep := ""
		if i == 0 {
			prep = "mkdir -p /out\n"
		}
		r.f("RUN %s<<'FACTORY_EOF'\nset -eu\n%s%s\nFACTORY_EOF\n", mount, prep, strings.TrimRight(m.StepScript(i), "\n"))
	}

	r.f("\n# ---- app ----\n")
	r.f("FROM %s\n", l.Base.Pinned())
	r.f("COPY --link --from=build /out/ %s/\n", strings.TrimSuffix(st.Spec.AppDir, "/"))
	r.config()
	r.out.Containerfile = r.b.Bytes()
	return &r.out, nil
}

// url applies the org's mirrors to a download URL.
func (r *renderer) url(u string) string {
	return manifest.Rewrite(r.m.Spec.Mirrors, u)
}

func allSame(m map[string]lock.Artifact) bool {
	var first *lock.Artifact
	for _, a := range m {
		if first == nil {
			first = &a
			continue
		}
		if a != *first {
			return false
		}
	}
	return true
}

func normMode(m, def string) string {
	if m == "" {
		return def
	}
	if len(m) == 3 {
		return "0" + m
	}
	return m
}

// shq single-quotes s for sh when it contains anything beyond a safe set.
func shq(s string) string {
	safe := true
	for _, c := range s {
		ok := c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || strings.ContainsRune("/._-+=:,@%", c)
		if !ok {
			safe = false
			break
		}
	}
	if safe && s != "" {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// copyArgs uses the JSON form of COPY when a path needs quoting.
func copyArgs(src, dst string) string {
	if shq(src) == src && shq(dst) == dst {
		return src + " " + dst
	}
	return jsonArray([]string{src, dst})
}

// dq double-quotes s for ENV/LABEL, escaping what the Dockerfile parser would
// interpret.
func dq(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, `$`, `\$`, "\n", `\n`)
	return `"` + r.Replace(s) + `"`
}

func jsonArray(a []string) string {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(a)
	return strings.TrimSpace(b.String())
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
