// Package lock defines the lockfile: every input of an image, content-addressed.
package lock

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/northcutted/clearcutt-factory/internal/manifest"
)

const (
	Kind   = "Lock"
	header = "# Code generated by clearcutt-factory lock. DO NOT EDIT.\n"
)

// How a tool artifact's hash was established, strongest first.
const (
	VerifiedPinned       = "pinned"              // sha256 written in the manifest
	VerifiedChecksumFile = "checksum-file"       // publisher's checksum file
	VerifiedGitHubDigest = "github-asset-digest" // digest reported by the GitHub API
	VerifiedImageDigest  = "image-digest"        // content-addressed image
	VerifiedGoSumDB      = "go-sumdb"            // checked by the go command against sum.golang.org
	VerifiedNixSignature = "nix-signature"       // binary cache signature over each store path
	VerifiedTOFU         = "tofu"                // hashed on first download
	VerifiedUnverified   = "unverified"          // build scripts; output is whatever they produce
)

type Lock struct {
	APIVersion      string   `yaml:"apiVersion" json:"apiVersion"`
	Kind            string   `yaml:"kind" json:"kind"`
	InputsDigest    string   `yaml:"inputsDigest" json:"inputsDigest"`
	SourceDateEpoch int64    `yaml:"sourceDateEpoch" json:"sourceDateEpoch"`
	Builder         Builder  `yaml:"builder" json:"builder"`
	Base            Image    `yaml:"base" json:"base"`
	Packages        Packages `yaml:"packages,omitempty" json:"packages,omitempty"`
	Tools           []Tool   `yaml:"tools,omitempty" json:"tools,omitempty"`
	// App pins what an app builds with; its Base is the stack's run image.
	App *App `yaml:"app,omitempty" json:"app,omitempty"`
}

// App is the locked stack of an app.
type App struct {
	Stack string `yaml:"stack" json:"stack"`
	// StackDigest ties the lock to the stack definition it was made with.
	StackDigest string `yaml:"stackDigest" json:"stackDigest"`
	// Build is the image the stack's steps run in.
	Build Image `yaml:"build" json:"build"`
	// RunPlatforms are the run image's per-platform digests, written into
	// the app image's base annotations so a rebase can find its base.
	RunPlatforms map[string]string `yaml:"runPlatforms" json:"runPlatforms"`
}

type Builder struct {
	BuildKit Image `yaml:"buildkit" json:"buildkit"`
	Frontend Image `yaml:"frontend" json:"frontend"`
	Toolbox  Image `yaml:"toolbox" json:"toolbox"`
}

// Image is a reference as written plus the digest it resolved to.
type Image struct {
	Ref    string `yaml:"ref" json:"ref"`
	Digest string `yaml:"digest" json:"digest"`
}

// Pinned returns the reference with its digest, keeping the tag for readers,
// e.g. cgr.dev/x/y:latest@sha256:…. The digest is what gets pulled.
func (i Image) Pinned() string {
	ref, _, _ := strings.Cut(i.Ref, "@")
	return ref + "@" + i.Digest
}

// RepoOf strips the tag and digest from an image reference.
func RepoOf(ref string) string {
	if i := strings.Index(ref, "@"); i >= 0 {
		ref = ref[:i]
	}
	if i := strings.LastIndex(ref, ":"); i > strings.LastIndex(ref, "/") {
		ref = ref[:i]
	}
	return ref
}

// Package managers.
const (
	ManagerAPK = "apk"
	ManagerAPT = "apt"
	ManagerDNF = "dnf"
)

type Packages struct {
	// Manager is apk, apt, or dnf.
	Manager string `yaml:"manager,omitempty" json:"manager,omitempty"`
	// InputsDigest covers what package resolution depends on (base digest,
	// repositories, requested packages, platforms) so unchanged pins are reused.
	InputsDigest string `yaml:"inputsDigest,omitempty" json:"inputsDigest,omitempty"`
	// Distro is the base's os-release ID and VERSION_ID, e.g. debian-13.
	Distro string `yaml:"distro,omitempty" json:"distro,omitempty"`
	// Snapshot is the archive snapshot apt resolved against (Debian).
	Snapshot     string               `yaml:"snapshot,omitempty" json:"snapshot,omitempty"`
	Repositories []string             `yaml:"repositories,omitempty" json:"repositories,omitempty"`
	Platforms    map[string][]Package `yaml:"platforms,omitempty" json:"platforms,omitempty"`
}

// EffectiveManager treats locks written before managers existed as apk.
func (p Packages) EffectiveManager() string {
	if p.Manager == "" {
		return ManagerAPK
	}
	return p.Manager
}

// Package is one pinned package. apk packages are fetched by apk from the
// recorded repositories and identified by Checksum; apt and dnf packages are
// downloaded from URL and verified against SHA256.
type Package struct {
	Name     string `yaml:"name" json:"name"`
	Version  string `yaml:"version" json:"version"`
	Arch     string `yaml:"arch" json:"arch"`
	Checksum string `yaml:"checksum,omitempty" json:"checksum,omitempty"`
	URL      string `yaml:"url,omitempty" json:"url,omitempty"`
	Filename string `yaml:"filename,omitempty" json:"filename,omitempty"`
	SHA256   string `yaml:"sha256,omitempty" json:"sha256,omitempty"`
	Origin   string `yaml:"origin,omitempty" json:"origin,omitempty"`
	License  string `yaml:"license,omitempty" json:"license,omitempty"`
	Repo     string `yaml:"repo,omitempty" json:"repo,omitempty"`
}

type Tool struct {
	Name         string `yaml:"name" json:"name"`
	From         string `yaml:"from" json:"from"`
	Version      string `yaml:"version,omitempty" json:"version,omitempty"`
	Verification string `yaml:"verification" json:"verification"`
	// SpecDigest ties this entry to the manifest tool spec it was resolved from.
	SpecDigest string `yaml:"specDigest" json:"specDigest"`
	// Artifacts are per-platform downloads (url, github-release).
	Artifacts map[string]Artifact `yaml:"artifacts,omitempty" json:"artifacts,omitempty"`
	// Image is the pinned source (oci) or builder (go, build) image.
	Image *Image `yaml:"image,omitempty" json:"image,omitempty"`
	// Package is the Go package path (go).
	Package string `yaml:"package,omitempty" json:"package,omitempty"`
	// Repo is owner/name for github-release, used for the SBOM purl.
	Repo string `yaml:"repo,omitempty" json:"repo,omitempty"`
	// Nixpkgs is the locked flake reference (nix).
	Nixpkgs string `yaml:"nixpkgs,omitempty" json:"nixpkgs,omitempty"`
	// Nix is the per-platform store path and its closure (nix).
	Nix map[string]NixOutput `yaml:"nixStore,omitempty" json:"nixStore,omitempty"`
}

// NixOutput is a store path and everything it references.
type NixOutput struct {
	Path    string    `yaml:"path" json:"path"`
	Closure []NixPath `yaml:"closure" json:"closure"`
}

// NixPath is one store path with the hash its signature covers.
type NixPath struct {
	Path    string `yaml:"path" json:"path"`
	NarHash string `yaml:"narHash" json:"narHash"`
}

type Artifact struct {
	URL    string `yaml:"url" json:"url"`
	SHA256 string `yaml:"sha256" json:"sha256"`
	// Extract is the path of the binary inside the downloaded archive, if any.
	Extract string `yaml:"extract,omitempty" json:"extract,omitempty"`
}

// Read loads a lockfile.
func Read(path string) (*Lock, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var l Lock
	dec := yaml.NewDecoder(bytes.NewReader(b))
	dec.KnownFields(true)
	if err := dec.Decode(&l); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if l.APIVersion != manifest.APIVersion || l.Kind != Kind {
		return nil, fmt.Errorf("%s: expected apiVersion %q and kind %q", path, manifest.APIVersion, Kind)
	}
	return &l, nil
}

// Marshal renders the lockfile deterministically.
func (l *Lock) Marshal() []byte {
	var buf bytes.Buffer
	buf.WriteString(header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	_ = enc.Encode(l)
	return buf.Bytes()
}

// Write saves the lockfile.
func (l *Lock) Write(path string) error {
	return os.WriteFile(path, l.Marshal(), 0o644)
}

// Tool returns the locked entry for name.
func (l *Lock) Tool(name string) *Tool {
	for i := range l.Tools {
		if l.Tools[i].Name == name {
			return &l.Tools[i]
		}
	}
	return nil
}

// Inputs is everything in the manifest and org profile that affects resolution.
// Changing any of it makes the lock stale.
type Inputs struct {
	Base           string          `json:"base"`
	Platforms      []string        `json:"platforms"`
	PackageManager string          `json:"packageManager,omitempty"`
	Repositories   []string        `json:"repositories"`
	Packages       []string        `json:"packages"`
	Tools          []manifest.Tool `json:"tools"`
	BuildKit       string          `json:"buildkit"`
	Frontend       string          `json:"frontend"`
	Toolbox        string          `json:"toolbox"`
	// Apps: the stack's build image and definition.
	Build string `json:"build,omitempty"`
	Stack string `json:"stack,omitempty"`
}

func InputsOf(m *manifest.Manifest, o *manifest.Org) Inputs {
	in := Inputs{
		Base:           m.Spec.Base,
		Platforms:      m.Spec.Platforms,
		PackageManager: m.Spec.PackageManager,
		Repositories:   m.Spec.Repositories,
		Packages:       m.Spec.Packages,
		Tools:          m.Spec.Tools,
		BuildKit:       o.Builder.BuildKit,
		Frontend:       o.Builder.Frontend,
		Toolbox:        o.Builder.Toolbox,
	}
	if m.Stack != nil {
		in.Build = m.Stack.BuildRef
		in.Stack = StackDigest(m.Stack)
	}
	return in
}

// StackDigest identifies a stack definition. The smoke test doesn't shape
// the image, so changing it doesn't make locks stale.
func StackDigest(s *manifest.Stack) string {
	spec := s.Spec
	spec.Test = nil
	return Digest(struct {
		Name string
		Spec manifest.StackSpec
	}{s.Metadata.Name, spec})
}

func (in Inputs) Digest() string { return Digest(in) }

// Digest hashes the JSON encoding of v.
func Digest(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	sum := sha256.Sum256(b)
	return "sha256:" + hex.EncodeToString(sum[:])
}
